### ISSUE TITLE
dask-pytorch

### ISSUE THREAD

**Issue by hhuuggoo** [dask/community#103]
I'm starting to put together a dask pytorch package.  It's pretty light, it just uses dask to bootstrap pytorch workers for DDP parallel training.

Just dropping a note here in case anyone is interested.  We can migrate it to the dask org in the future if there is interest.  It is currently here:

https://github.com/saturncloud/dask-pytorch

(but there is no code pushed yet)

**Comment by datametrician** [comment]
@EvenOldridge @quasiben

**Comment by hhuuggoo** [comment]
closing because https://pypi.org/project/dask-pytorch/ is out.  still really basic, but functional.  cc @skirmer

**Comment by jakirkham** [comment]
Link to the repo ( https://github.com/saturncloud/dask-pytorch ) if people want to peruse 🙂

**Comment by TomAugspurger** [comment]
Thanks for sharing!

Is there any interest in moving it under the Dask GitHub organization? I don't believe we have any official policy on what to do here, though it may have come up before. (At some point I can set up the DNS for torch.dask.org to link to the docs, but it'll be a while).

One other thing, I was surprised to see the "Project Homepage" link on PyPI (set at https://github.com/saturncloud/dask-pytorch/blob/b8ff4045acbdf26048e83ac3d6105752acdfba58/setup.py#L37) take you to saturncloud.io. Typically that would take you to either the GitHub repository or the docs page.

I'm really looking forward to playing with this.

**Comment by skirmer** [comment]
Thanks @TomAugspurger for catching that link thing- totally a mistake on my part, we'll fix it asap. As for moving it under Dask, I think that would be a good idea! Let me talk to the rest of the team and see how folks feel.

**Comment by skirmer** [comment]
We just pushed v0.1.1 to fix that links issue and a couple other small bugs. Sounds like everyone is happy to move the project under Dask as well. I'll link up with @jsignell to figure out how we do that smoothly!

**Comment by jsignell** [comment]
Is there any interest in moving it under the Dask GitHub organization?

I'll open a new issue in community to make sure that everybody agrees that the repo should move under dask.
