### ISSUE TITLE
improving LightGBM, XGBoost experience with Dask

### ISSUE THREAD

**Issue by jameslamb** [dask/community#104]
:wave: hello from Chicago!

I'm a [LightGBM](https://github.com/microsoft/LightGBM) maintainer and an engineer at [Saturn Cloud](https://www.saturncloud.io/s/). I'd like to devote some cycles to improving the experience of using XGBoost and LightGBM on Dask.

I'm planning to talk with the XGBoost maintainers about helping out on the issues noted in https://github.com/dask/dask-xgboost/issues/39 , and starting a similar discussion proposing that we migrate https://github.com/dask/dask-lightgbm into LightGBM directly and maintain it there.

Success for this would look like formally deprecating `dask-xgboost` and `dask-lightgbm` eventually and focusing all development in XGBoost and LightGBM (similar to how [xgboost-spark](https://github.com/dmlc/xgboost/tree/master/jvm-packages) and [xgboost-flink](https://github.com/dmlc/xgboost/tree/master/jvm-packages/xgboost4j-flink) are maintained in the main `xgboost` project).

What do folks here think about this? Are there other groups besides the maintainers of projects I've mentioned above that should be involved in this conversation?

Thanks for your time and consideration.

**Comment by TomAugspurger** [comment]
Thanks for opening this. I'm generally +1 on the core libraries (XGBoost, LightGBM) handling this if they're willing.

There might be some building blocks that should go into `dask.distributed` (e.g. https://github.com/dask/distributed/issues/3075).

cc @striajan and @sfinxCZ from the dask-lightgbm side.

**Comment by martindurant** [comment]
Great to hear from you. I think both these efforts are seen as high profile and important from the community's point of view.

Yes, this is probably the best place to start the conversation aside from the two repos (but maybe xref on dask-ml for a slightly different set of eyes). If you want a more general conversation around the strategy and Dask's involvement in the projects, you might want t attend our community meeting on the first Thursday of the month.

**Comment by SfinxCZ** [comment]
Hello @jameslamb,

great to hear that you are interested in helping us with the dask-lightgbm package. 

The idea of merging dask-lightgbm into main LightGBM repo seems reasonable to me. I agree with @TomAugspurger that main building blocks could be moved to `dask.distributed`. Another option is to move the common parts of the code to `dask-ml` which could be then set as optional dependency for the LightGBM package.

Second option that came to mi mind is to merge dask-xgboost and dask-lightgbm into single library (or moving to dask-ml), since a lot of the code can be reused, and specify LightGBM and xgboost as its optional dependencies and use it as middle-man between LightGBM,XGBoost and Dask libraries.

In general I like the idea. The only thing that I am not sure is where to separate the libraries and what should be maintained where. What are your plans (in LightGBM) for supporting different frameworks for distributed computing? Do you have/plan to have support for spark, flink, etc.? If you already have the support in your code, the effort you proposed could follow similar path.

**Comment by kkraus14** [comment]
cc @ramitchell @hcho3 @trivialfis from the xgboost side

**Comment by jameslamb** [comment]
Thanks!

adding @guolinke , @StrikerRUS from LightGBM

> What are your plans (in LightGBM) for supporting different frameworks for distributed computing? Do you have/plan to have support for spark, flink, etc.?

Today in LightGBM, the only option for distributed training that is maintained in the main project is our own ([`LightGBM::network`](https://github.com/microsoft/LightGBM/tree/3454698efe92ee57ea7afbcb3578f8850d132adb/src/network)), similar to how `xgboost` has [`rabit`](https://github.com/dmlc/xgboost/tree/master/rabit).

We produce a library for JVM languages [using SWIG](https://github.com/microsoft/LightGBM/blob/3454698efe92ee57ea7afbcb3578f8850d132adb/CMakeLists.txt#L345-L380). This is then used by the [`mmlspark`](https://github.com/Azure/mmlspark/tree/master) project to provide a Spark interface for LightGBM. I'm not aware of any Flink integration with LightGBM...I can at least confidently say there isn't one maintained in `microsoft/LightGBM`.

LightGBM doesn't currently directly support Dask...users who want to use LightGBM with Dask go to `dask-lightgbm`, maintained in `dask/dask-lightgbm`.

There are also [`kubeflow fairing operators`](https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/frameworks/lightgbm.py) for LightGBM, maintained in `kubeflow/fairing`.

<hr>

> Second option that came to mind is to merge dask-xgboost and dask-lightgbm into single library (or moving to dask-ml), since a lot of the code can be reused

I think that keeping the work in the `xgboost` and `LightGBM` repos is a better option, since those projects know the most about their own distributed training setup (`rabit` for `xgboost`, [`LightGBM::network`](https://github.com/microsoft/LightGBM/tree/3454698efe92ee57ea7afbcb3578f8850d132adb/src/network) for `LightGBM`). And then looking for opportunities to reuse as much code from `distributed` and `dask-ml` as possible, for example https://github.com/dask/distributed/issues/3075 that @TomAugspurger mentioned.

This seems like the conclusion that this thread reached: https://github.com/dask/dask-xgboost/issues/39

I think doing this also reduces the difference between the experience with, say, `lightgbm` vs. `dask-lightgbm`.

One reason that I've opened this issue is to say that I'm willing to do the legwork to coordinate between XGBoost and LightGBM to borrow from each other and to find opportunities to push things from the modelling frameworks upstream into `distributed` or `dask-ml`.

**Comment by SfinxCZ** [comment]
I've checked the xgboost code for dask integration and it seems reasonable to use the same approach.

So, I am ok that dask-lightgbm functionality should be merged directly into LightGBM core library.

**Comment by datametrician** [comment]
Has anyone discussed deprecating `dask-xgboost` to avoid confusion?

**Comment by TomAugspurger** [comment]
Yeah, at https://github.com/dask/dask-xgboost/issues/39.

Last I checked there were a few issues / missing features from
dmlc/xgboost, but the eventual goal is to deprecate dask-xgboost when those
are resolved.

**Comment by jameslamb** [comment]
Yep! They're listed in this comment: https://github.com/dask/dask-xgboost/issues/39#issuecomment-681974273.

I have some free cycles to work on this, and @hcho3 I'm willing to help with those issues in XGBoost if you need another set of hands :grinning:

**Comment by hcho3** [comment]
@jameslamb Thanks for your offer. Currently the only blocking issue is https://github.com/dmlc/xgboost/issues/5765. `xgboost.dask` now supports early stopping and `predict_proba()`.

**Comment by jameslamb** [comment]
> I've checked the xgboost code for dask integration and it seems reasonable to use the same approach.
> 
> So, I am ok that dask-lightgbm functionality should be merged directly into LightGBM core library.

Thanks very much @SfinxCZ ! I've talked with other LightGBM maintainers in https://github.com/microsoft/LightGBM/issues/2791 and they're open to the idea as well 🎉 

Could you open a pull request into https://github.com/microsoft/LightGBM with the contents of `dask_lightgbm`?

We can talk in the PR about:

* which code should be merged
* how much you and other `dask-lightgbm` maintainers would want to still be involved once that code makes it into a LightGBM release
* transferring any ideas you have for improvements to issues in the LightGBM backlog


And actually, before we do that...are there other `dask-lightgbm` maintainers that we need to get agreement from as well?

**Comment by datametrician** [comment]
@jameslamb does that mean LightGBM will potentially have MNMG support :)

**Comment by jameslamb** [comment]
@datametrician it could be a route to that, yes

**Comment by SfinxCZ** [comment]
@jameslamb I've created new PR https://github.com/microsoft/LightGBM/pull/3515 where I've put the core functionality + unit tests. I would suggest to move the discussion regarding the migration of the code to the PR.

Regarding other contributors, I am not sure if others are interested in the discussion (maybe @striajan ?), but I would suggest to start the moving process and if others choose to remain silent I would assume that they agree :-).

**Comment by mrocklin** [comment]
+1 for lazy consensus.  In general I think that it's fine to proceed.

**Comment by striajan** [comment]
Thanks for including me into the discussion. To put my two cents in, integration of this repository into the main LightGBM repository sounds great, even though I do not plan to work on it in the future because of moving to a different company. Maybe @shcherbin would be interested in this discussion?

**Comment by hcho3** [comment]
The last blocking issue (dmlc/xgboost#5765) has been addressed, so we can proceed with migration from dask-xgboost to xgboost.dask.

**Comment by jameslamb** [comment]
Wanted to update those following this issue.

Thanks to a lot of effort from @SfinxCZ , the main parts of `dask-lightgbm` were merged into LightGBM today: https://github.com/microsoft/LightGBM/pull/3515.

I think there will be substantial changes to it between now and the 3.2.0 release of `lightgbm`, but it's there now 😀

**Comment by jameslamb** [comment]
I've opened up a Request For Comment in LightGBM, about how LightGBM should get the Dask client you want to use. If anyone here has time / interest, we'd appreciate comments at https://github.com/microsoft/LightGBM/issues/3808.

Thanks to @jsignell for already adding her opinion.

**Comment by jameslamb** [comment]
`lightgbm` 3.2.0 was released today 🎉 

This is the first release of `lightgbm` that includes a Dask integration (which began with @SfinxCZ graciously upstreaming `dask-lightgbm` in https://github.com/microsoft/LightGBM/pull/3515).

You can see the full details of this release at https://github.com/microsoft/LightGBM/releases/tag/v3.2.0.

Thanks to everyone on this issue for your help. I especially want to shout out @ffineis, @jmoralez, and @StrikerRUS for putting a lot of time and energy into this first `lightgbm.dask` release.

**Comment by jakirkham** [comment]
Thanks for the update James! 😀Nice work everyone! 👏

Should we go ahead and close this issue out then? 😉

**Comment by mrocklin** [comment]
Woot!

**Comment by jameslamb** [comment]
> Should we go ahead and close this issue out then?

@jakirkham I think it can be closed, yeah!

There is still some work to be done but all the relevant conversations are already happening in the specific projects that might be affected, so I don't think we need this issue any more.

* archiving `dask-xgboost`: https://github.com/dask/dask-xgboost/issues/80
* archiving `dask-lightgbm`: https://github.com/dask/dask-lightgbm/pull/30
* removing the `xgboost` namespace from `dask-ml`: https://github.com/dask/dask-ml/issues/797#issuecomment-795278333

I'm going to close this out, thanks again to everyone for your help!

**Comment by jakirkham** [comment]
Yeah it sounds like with XGBoost that `dask-xgboost` issue will get closed out on the next release. Looks like `dask-lightgbm` just needs release. Cc'd some folks on the Dask-ML issue to see if they have thoughts there
