### ISSUE TITLE
Dask in HPC Workshop; Dask tutorial presenter?

### ISSUE THREAD

**Issue by dwhswenson** [dask/community#110]
[I hope this is the right venue for this discussion; if not, please redirect me to the right place!]

@ocaisa and I are organizing a virtual workshop/webinar series on high performance computing using Dask. We're hoping to find someone here who would be willing to present an introduction to Dask.

The plan for this workshop is to present three packages:

* Dask
* Dask-Jobqueue (@willirath has accepted the invitation to present)
* [Jobqueue-Features](https://github.com/E-CAM/jobqueue_features), which adds functionality to Dask-Jobqueue for certain workflows (@AdamWlodarczyk has accepted the invitation to present)

We held a similar (in-person) workshop in Turin in July 2019, with the same speakers for Dask-Jobqueue and Jobqueue-Features. We're hoping someone (or more than one) in the Dask community might volunteer to present Dask.

The workshop will be virtual, and we plan to hold it in late January/early February. Exact dates will be determined by availability of speakers, but we do expect presentations to start around 14:00 UTC. We're funded by the EU, so we must pick a time that works in Europe, but by starting at 9am Eastern, we hope we can also pick up some US participants.

Much of the audience would be computational scientists, likely with many from computational chemistry; mostly PhD students and post-docs. Many will be new to Dask; so I think this might fit in well as a "special episode" of the regular online tutorials (as discussed in #57). We're still looking into technical details, but we hope to have a small Zoom "classroom" of a few participants who could provide more direct feedback, along with a simultaneous YouTube live stream.

I hope this will be of interest to some of you!

**Comment by jacobtomlinson** [comment]
I'm in the UK and would be happy to virtually present a Dask tutorial [similar to this one](https://www.youtube.com/watch?v=_u0OQm9qf_A).

When we've run this tutorial online in the past we've had more than one person so that one can present and another can take questions in the chat. So it would be good if someone else could help me.

**Comment by willirath** [comment]
Sounds great! I'd definitely like to join as the second person for the Dask tutorial.

**Comment by mrocklin** [comment]
I'm very glad to see people organizing workshops like this :)

**Comment by dwhswenson** [comment]
Thanks @jacobtomlinson and @willirath! That's great. @ocaisa and I can also help with bringing questions to your attention (I understand that part of @willirath's role in there will be as much to point to relevant parts in the docs when the docs answer a question.)

Now we mainly need to set dates/times that work for all the speakers. I need to meet with @ocaisa to double check our schedules, but I think that any day starting Tue 19 Jan 2021 and up to Fri 5 Feb (though preferably in January) would work for the Dask presentation. Ideally, we can have the three presentations over the course of 3 weeks, on the same day of the week and at the same time, so that may require coordinating with a Doodle poll. @jacobtomlinson : How should I send that to you? (I have email addresses for @willirath [and the colleague who may help him, whose GitHub name I don't know] and for @AdamWlodarczyk.)

**Comment by willirath** [comment]
> [and the colleague who may help him, whose GitHub name I don't know]

Pinging @kathoef :)

**Comment by jacobtomlinson** [comment]
Feel free to use the email address from [here](https://github.com/dask/helm-chart/blob/master/dask/Chart.yaml).

**Comment by dwhswenson** [comment]
We now have a tentative schedule:

* Thu 21 Jan 2021 14:00 UTC: Dask (@jacobtomlinson and @willirath)
* Thu 4 Feb 2021 14:00 UTC: Dask-Jobqueue (@willirath  and @kathoef )
* Thu 11 Feb 2021 14:00 UTC: Jobqueue-Features (@AdamWlodarczyk and @ocaisa)

In the near future, we'll have a workshop page on the [CECAM website](http://www.cecam.org). I'll continue to post updates here for the broader community. Thanks everyone!

**Comment by guillaumeeb** [comment]
Just wanted to say this is really great to see this!

@willirath will you be using materials you already shared?

@dwhswenson I understand that the youtube stream link will be public?

**Comment by willirath** [comment]
Yes, I think I’ll reuse large parts of the materials I’ve shared earlier.

**Comment by dwhswenson** [comment]
> I understand that the youtube stream link will be public?

Absolutely. The live streams will be public. The resulting videos will be publicly available on YouTube after the sessions. I expect we'll also put a copy of them into the [E-CAM training portal](http://training.e-cam2020.eu/), which documents all of the training activities from the project that funds us. Finally, we're happy to provide speakers with copies of their talks in the best resolution we have, for the speakers to do with as they please.

We may have a few student participants in the Zoom as well, to give the speaker some sort of more immediate audience. Those participants will need to have registered for the workshop on the CECAM page (coming soon!) We'll *recommend* registration for everyone, but that is just so we can send out reminder emails before each event and so we can send out a feedback survey at the end. It is in no way required for participation. Registration is free of charge and open to the public.

**Comment by willirath** [comment]
@dwhswenson I have some vague memory that I've seen technical details (for the participants of the workshop) already, but I cannot find it now. Is this already available somewhere?

**Comment by ocaisa** [comment]
@willirath The workshop details are at https://www.cecam.org/workshop-details/1022

For the technical details, you might mean the tutorial setup that we have in our repo https://github.com/E-CAM/jobqueue_features#tutorial

**Comment by jakirkham** [comment]
cc @jglaser (in case this is of interest 😉)
