### ISSUE TITLE
Should we have a Dask Incubator GitHub org?

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#115]
I've been thinking a bit about issue #111 and wondered if we should consider creating a `dask-incubator` org for new projects to live on GitHub until they show a certain level of maturity?

Some projects recently have been upstreamed into places other than Dask; XGBoost and LightGBM for example. These are projects which could live in the incubator and then never actually end up in the main Dask org.

I also remember some early conversations with @mrocklin about `dask-cloudprovider` where we discussed when the project should move over and when it was appropriate to link the docs from the main Dask docs. Perhaps moving from the incubator org to the main org is the point where docs links should be added.

**Comment by mrocklin** [comment]
I'm open to the idea.  What are some projects that would make sense to put
there today?  Also, I think that Numba did something recently, we might
look at what their experience was like.

**Comment by jacobtomlinson** [comment]
Well we discussed moving Saturn Cloud's Pytorch work to the main org, then decided against it. So that is the kind of situation I'm thinking of.

I expect `dask-cloudprovider` could've been considered incubating until the big three cloud providers were implemented at the end of 2020.

**Comment by jrbourbeau** [comment]
I'm also open to this idea. FWIW I was thinking about this a while ago for `dask-optuna` and reserved the [`dask-contrib`](https://github.com/dask-contrib) GitHub organization (similar to [`xarray-contrib`](https://github.com/xarray-contrib) and [`scikit-learn-contrib`](https://github.com/scikit-learn-contrib)).

**Comment by mrocklin** [comment]
cc @nils-braun

**Comment by jacobtomlinson** [comment]
Nice planning @jrbourbeau!

In terms of naming, I feel like `contrib` suggests the package is not maintained by the core team but is endorsed. Whereas `incubator` is a core project but is not yet stable/mature.

I'm not sure what image we want to present here.

**Comment by nils-braun** [comment]
Great idea! (and thanks for the mention, I would be more than happy if I can apply for an incubator project in the future :-))

I am not a member of the dask core community, so I do not want to give any opinions or directions, but as @mrocklin mentioned other incubator projects, here are some ideas from others:

[Apache Incubator](https://incubator.apache.org/)
* Provide a [cookbook](http://incubator.apache.org/cookbook/) to decide, if one should apply for an incubator project. Probably a bit too much for Dask, but some (written) guidance would be nice.
* They delegate (fixed?) mentors for each incubator project, which I think is a nice idea but of course also adds more work to the core team
* benefits of being an Apache incubator: (among others) using the infrastructure and services (mailing lists, JIRA, Apache governance). 

[Open Source Initiative](https://wiki.opensource.org/bin/Working+Groups+%26+Incubator+Projects/)
* there is an elected board that decides which projects to fund. What would be the decision process for Dask incubator projects?
* there can never be two incubator projects with the same content in the OSI community. Would be out for debate if Dask should be so "limiting".

Not directly related, but: [Jupyter Enhancement Proposals](https://github.com/jupyter/enhancement-proposals/blob/master/jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.md)
* I like the fact that everything is done via GitHub PRs and issues and templates in markdown are already prepared

**Comment by jakirkham** [comment]
No objection from me if we have use cases. For one project maybe a note in the README is sufficient. For multiple having an org makes sense.

**Comment by jrbourbeau** [comment]
> In terms of naming, I feel like contrib suggests the package is not maintained by the core team but is endorsed. Whereas incubator is a core project but is not yet stable/mature.

Thanks for pointing that out. I totally agree we'll want to pick a name that aligns well with the intent of the org.

One option would be to have the GitHub org be a place for third party Dask-related projects from the community. These aren't necessarily maintained by the core Dask team. As some projects mature and gain traction they can be added to the Dask org and be "fully endorsed" (for lack of a better term) by the Dask maintainers. Other projects would live in the Dask-contrib / -incubator org indefinitely. For a concrete example of this type of relationship, see the `click-contrib` GitHub org https://click.palletsprojects.com/contrib/

Just throwing that out there as one possible path forward. Totally open to suggestions from others 

> No objection from me if we have use cases

Today I think a couple of good candidates would be [`dask-sql`](https://github.com/nils-braun/dask-sql) and [`dask-pytorch-ddp`](https://github.com/saturncloud/dask-pytorch-ddp). Other suggestions are certainly welcome

**Comment by jacobtomlinson** [comment]
Another good candidate could be [itamarst/dask-memusage](https://github.com/itamarst/dask-memusage/)  (highlighted in dask/dask-blog#20)

**Comment by jsignell** [comment]
Do we need to write some policy docs for dask-contrib?

**Comment by jacobtomlinson** [comment]
Probably!

**Comment by jrbourbeau** [comment]
> Do we need to write some policy docs for dask-contrib?

Indeed we should. Even having a few paragraphs, for example something like https://click.palletsprojects.com/en/7.x/contrib/, would be useful. We should think about community guidelines, like a code of conduct, too. @quasiben mentioned a reasonable thing we could do is just have the dask-contrib org adopt the dask org code of conduct.

**Comment by martindurant** [comment]
Right: the difference should not be in how we interact, but in the stability of the code or how closely tied to Dask it is.

**Comment by stsievert** [comment]
:+1: to the "dask-contrib" name. I have a package ([stsievert/adadamp][1]) that I think should be labeled "a nice integration of Dask and PyTorch." I think labeling it as "a project that Dask will/might merge into Dask-ML soonish" seems like an overreach and/or *very* premature.

Should both the "dask-contrib" and "dask-incubator" organizations be reserved/created? If I had to choose one, I'd choose "dask-contrib" because that name implies more projects can join.

[1]:https://github.com/stsievert/adadamp

**Comment by jakirkham** [comment]
James reserved `dask-contrib` ( https://github.com/dask/community/issues/115#issuecomment-755419932 )

I don't think anyone has done anything with `dask-incubator`, but maybe we don't plan to use that anyways

**Comment by jacobtomlinson** [comment]
I've raised dask/dask#7354 to add some policy to the docs. Feedback is must appreciated.

**Comment by jsignell** [comment]
Should we close this issue?

**Comment by jacobtomlinson** [comment]
Good idea. Discussion can move over to the PR.
