### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#12]
Next month is [hacktoberfest](https://hacktoberfest.digitalocean.com/).

This means there will be lots of people hunting for open source issues to solve and any issues tagged with `hacktoberfest` will be elevated.

I've found in past years that taking some time to curate some well-written issues and label them up has paid off. Especially with things that fresh eyes on the project are good at helping with: documentation, examples, usability, UX, etc.

Is there any interest in this?

**Comment by jacobtomlinson** [comment]
This came up elsewhere and ended up having a longer discussion. Here is a summary that may also be helpful here.

> I’ve had success with [hacktoberfest] in the past on other projects.
> 
> However there are some things to bear in mind:
> - Issues tagged with hacktoberfest generally need to be very well written and basically lay out the solution in order to get people to bite
> - Contributions will be mostly drive-by contributions where the author has no interest in continued maintenance once they have their hacktoberfest tshirt
> - Tagging issues with the hacktoberfest label will attract many first time contributors who will ask for guidance on using git, GitHub, etc
> - If you spend too long going back and forth in a review they will look for “easier” issues to get their tshirt
> 
> The upsides of getting many fresh eyes on the project are:
> 
> - Fresh eyes are often better at improving docs, especially in highlighting what is missing
> - If you thoroughly lay out how to add a certain feature, but also ask for tests to be added then that can be helpful
> - Some people will be excited about the project and stick around in the long term
> I guess my main point is I find it a good marketing vehicle for a project. And it can be good for giving back to the community in the long term by teaching others how to contribute. But it’s not a great way to get high quality contributions.

**Comment by jrbourbeau** [comment]
Seeing as October has come and gone, I'm going to close this issue. Apologies for not replying here. Perhaps we can put something together next year. 

Hope you had a good Hacktober : )
