### ISSUE TITLE
Dask Array team

### ISSUE THREAD

**Issue by mrocklin** [dask/community#123]
Hi Folks, 

I've been seeing an increase in the number of tricky/fun array computing questions recently.  These involve operations like blockwise, tensordot, chunking and other topics that require a bit of deep thinking and a strong background with the numpy computing model.

We have a lot of people in the community who seem to like these problems, but understandably don't watch the full issue tracker.  I would like to create a team, @dask/array which gets pinged on some of these issues.  I'm cc'ing a few people here, to see if they would be interesting in being part of this github team.  If so, please either add a comment here, or else click the Rocket Ship emoji on this comment.

cc @shoyer @jakirkham @pentschev @bmerry @sofron @sofroniewn @jhamman @rabernat @sjperkins @jskenyon @hmaarrfk @tomwhite @eric-czech

**Comment by jakirkham** [comment]
Would it be of interest to do something similar for Dataframes ( @dask/dataframe )?

**Comment by bmerry** [comment]
You can add me (I clicked the rocket) but I will probably ignore a lot of it as Dask is something I only sporadically have time to work on - generally when I bump into issues with our specific use cases.

**Comment by mrocklin** [comment]
OK, so apparently after 11 people GitHub stops listing individual names on emojis.  I've created the team, and twelve of thirteen people are on it.  If you :rocket: 'd recently you might want to make a comment.

I'm going to close this issue though.  I think that the jobs here is mostly done.

**Comment by ravwojdyla** [comment]
@mrocklin I would be interested as well. Thanks!

**Comment by jakirkham** [comment]
I think you were added Rafal, but you may need to accept a GitHub invitation to get it.

**Comment by mrocklin** [comment]
I added @ravwojdyla after his recent comment.  It is definitely a good idea to comment at this stage.  I'm going to stop tracking this issue otherwise.

**Comment by JSKenyon** [comment]
I would be interested! Thanks!

**Comment by sjperkins** [comment]
I'm happy to pitch in too, time permitting.

**Comment by jakirkham** [comment]
Added. @JSKenyon, GitHub should send you an invite to accept the org, which would need to be accepted to join the team

**Comment by JSKenyon** [comment]
Done @jakirkham!

**Comment by hmaarrfk** [comment]
I would be interested as well. Thanks for making this more focused!

**Comment by eric-czech** [comment]
Hey @mrocklin, I'd like to be added too.  Apologies for the delay.

**Comment by jakirkham** [comment]
Both of you should be added. Please double check that you have accepted the invite. Details about how in ( https://github.com/dask/community/issues/125#issuecomment-770101412 )
