### ISSUE TITLE
Dask Dataframe team

### ISSUE THREAD

**Issue by jakirkham** [dask/community#125]
Recently we created an array team for folks interested in various array questions, issues, and proposed changes coming up. See issue for details ( https://github.com/dask/community/issues/123 ). Would like to propose doing the same thing for dataframes. In short if maintainer's see discussions that are of interest to this group, the team would be cc'd there to help promote visibility of relevant topics. If you would be interested in joining this team, please click the rocket ship icon on the OP. Copying a few people who may be interested in this (feel free to point others to this if this sounds interesting).

cc @TomAugspurger @kkraus14 @madsbk @rjzamora @jorisvandenbossche @gforsyth @mmccarty @raybellwaves @jsignell @jameslamb @randerzander @quasiben

**Comment by kkraus14** [comment]
@galipremsagar @brandon-b-miller @shwina @isvoid @rgsl888prabhu in case any of them are interested as well 😄

**Comment by mmccarty** [comment]
@jakirkham Yes please. (commenting because more than 11 people beat me to the 🚀 )

**Comment by jakirkham** [comment]
Thanks all! So I added 12 usernames I could see, but GitHub doesn't show who the next 4 are. Some of you are outside the org, so will need to accept the invite to join. For those of you that I missed, please comment here and we'll add you.

**Comment by rgsl888prabhu** [comment]
@jakirkham , please add me

**Comment by isVoid** [comment]
@jakirkham love to join!

**Comment by jakirkham** [comment]
Thanks Michael! Added 😄

**Comment by raybellwaves** [comment]
Happy to help (rocket # 17)

**Comment by jorisvandenbossche** [comment]
@jakirkham you can add my name as well

**Comment by jakirkham** [comment]
Added. Thanks all! 😄

**Comment by jakirkham** [comment]
If you haven't already, please make sure to check on your invitation to the team as described in comment ( https://github.com/dask/community/issues/125#issuecomment-770101412 ). Thanks! 😄
