### ISSUE TITLE
Adding the community repo to pinned repos on GitHub

### ISSUE THREAD

**Issue by jakirkham** [dask/community#132]
To ease navigation, it would be nice to pin this repo on GitHub. That said, I think there is a limit of 6 repos that can be pinned at a time and we are at that limit already. So if we do agree that pinning this is reasonable there would be a question of which of the current pinned repos would no longer be pinned. Thoughts? 🙂

**Comment by TomAugspurger** [comment]
I think dask-stories or dask-ml could be dropped.

**Comment by mrocklin** [comment]
I've dropped dask-stories and added community

**Comment by jakirkham** [comment]
Thanks Matt! 😄
