### ISSUE TITLE
Updated figures

### ISSUE THREAD

**Issue by jrbourbeau** [dask/community#135]
A while back a few of us had a diagram sprint (xref https://github.com/dask/marketing/issues/6) and produced several figures, some of which made their way to our docs and others which we wanted to work a bit more on before incorporating into the docs.

@mrocklin and I have been working with a designer to redo some of these figures to give an updated and consistent look across our docs, figures that are commonly used in talks/tutorials, etc. In addition, @jacobtomlinson also brought up that we might want to have a designer update about our existing [color palette](https://marketing.dask.org/en/latest/colors.html). 

Below I've included some initial work from the designer and am hoping to get feedback from the rest of the community that we can use to further iterate on these diagrams. To be clear there are other commonly used figures which I think would also benefit from an update. The figures below are just an initial batch so we can get feedback on things like color, style, etc.

# Color palette
<img width="1051" alt="Screen Shot 2021-03-11 at 2 19 29 PM" src="https://user-images.githubusercontent.com/11656932/110850588-8e975900-8275-11eb-8d5a-1f2bb380bef6.png">

# Cluster manager

<img width="993" alt="Screen Shot 2021-03-11 at 2 19 51 PM" src="https://user-images.githubusercontent.com/11656932/110850589-8f2fef80-8275-11eb-8158-c771f6880bc6.png">

# Dask overview

<img width="992" alt="Screen Shot 2021-03-11 at 2 20 07 PM" src="https://user-images.githubusercontent.com/11656932/110850590-8fc88600-8275-11eb-9b63-954a69a3d98a.png">

# Distributed overview 

<img width="766" alt="Screen Shot 2021-03-11 at 2 20 24 PM" src="https://user-images.githubusercontent.com/11656932/110850592-8fc88600-8275-11eb-8238-1c53d4d51108.png">

# Map reduce vs. task scheduling

<img width="1371" alt="Screen Shot 2021-03-11 at 2 20 39 PM" src="https://user-images.githubusercontent.com/11656932/110850594-90611c80-8275-11eb-96ad-d9caf76f4e16.png">

**Comment by quasiben** [comment]
Thanks for the update @jrbourbeau .  These look really great!  The full task scheduling graph looks little strange -- maybe a combination of array-sum and transpose-sum.  Though I think it gets the point across that Dask task scheduling looks very different from embarrassingly parallel and mapreduce

**Comment by jacobtomlinson** [comment]
Hooray for designers who know what they're doing! These look really nice.

A few notes:
- How were these created? Will it be possible for us to make new diagrams in the future that fit the same style, or will we need to get the designer back?
- I think recoloring the Python and Jupyter logos like that will be a violation of their brand guidelines.

**Comment by michelechambers** [comment]
> Hooray for designers who know what they're doing! These look really nice.
> 
> A few notes:
> 
> * How were these created? Will it be possible for us to make new diagrams in the future that fit the same style, or will we need to get the designer back?
These were created using Figma and can be modified using Figma. We chose Figma because it's pretty easy to use (as opposed to Adobe tools which are more complicated to use). We'd contribute both the final version and the Figma files. 
> * I think recoloring the Python and Jupyter logos like that will be a violation of their brand guidelines.
Good point. I'll put inquiries into those organizations and have the designer adjust accordingly. 

Jacob

**Comment by jacobtomlinson** [comment]
Awesome thanks!

**Comment by jakirkham** [comment]
Just to clarify, this is Figma ( https://www.figma.com ), right?

**Comment by jrbourbeau** [comment]
Yep https://www.figma.com is correct

**Comment by jrbourbeau** [comment]
Thanks all for the feedback! FYI we're hoping to send comments back to the designer at the end of day tomorrow -- so feel free to let us know if there are any more comment, questions, etc. you may have

Here are some initial thoughts I have:

- Overall I like the new figures and color palette! 
- The blue boxes with text might benefit from higher contrast between the text and background color. I don't have strong thoughts on how to do this (e.g. darker text vs. lighter background)
- In the "Dask overview" figure the top most blue rectangle says "Process" when it should say "Dask Array"
- In the "Map reduce vs. task scheduling" figure I'd like to see Prefect added to the "Full task scheduling" diagram (it's commonly used in the Dask ecosystem)
- In the "Distributed overview" figure there's a typo: "tasks to works for" should be "tasks to Workers for"
- In the "Cluster manager" figure there are some typos
    - "many Works" should be "many Workers"
    - "Abstracts pods" should be "abstract pods"
    - I don't think "Networking" needs to be capitalized

Additionally, many existing Dask talks, for example https://dask.org/slides, use a dark background. I'd like to ask the designer how difficult it would be to provide both light- and dark-background friendly version of each figure. If it turns out this requires a lot of extra work then I think a single version is totally okay, but if it's relatively straightforward a dark background version would be nice to have.

**Comment by mrocklin** [comment]
Thanks for handling this James and Michele.  

I would encourage people here to think more broadly as well.  Updating these figures was a test case to see how well this process worked.  Based on the feedback here it looks to be working pretty well (although we have yet to see these assets get finalized and deployed).  If so, I'd be happy pushing in this direction pretty far.  If people have thoughts on other parts of Dask's current visual identity and style that we should update I encourage them to express those thoughts (looking at you @jacobtomlinson ).  This is probably best done in another issue.  If that issue does get created I would welcome someone  sending me a personal e-mail with it (my github inbox is unfortunately infrequently tended to today).

**Comment by andersy005** [comment]
Great job to everyone involved! In the "Embarrassingly Parallel" figure, is it possible to add a few details on what "everything" in `everything supports this` is referring to?

**Comment by jrbourbeau** [comment]
Would something like "All projects support this" be more clear? For reference, the "Everything supports this" subtitle is supposed to be compared to the other subtitles like "Hadoop/Spark/Dask" and "Dask/Airflow"

**Comment by andersy005** [comment]
> Would something like "All projects support this" be more clear? 

In case the list of projects being compared isn't too long, wouldn't it be clearer to replace `everything/all projects support this` by `Hadoop/Spark/Dask/Airflow/Prefect` ??

**Comment by michelechambers** [comment]
> > * How were these created? Will it be possible for us to make new diagrams in the future that fit the same style, or will we need to get the designer back?
> 
> These were created using Figma and can be modified using Figma. We chose Figma because it's pretty easy to use (as opposed to Adobe tools which are more complicated to use). We'd contribute both the final version and the Figma files.
> 
> > * I think recoloring the Python and Jupyter logos like that will be a violation of their brand guidelines.
> 
> Good point. I'll put inquiries into those organizations and have the designer adjust accordingly.

We have obtained permission from Python (see below) for the change to the logo. For Jupyter, we're going to use their primary logo since they have not reviewed yet and recommended we use one of their approved logos. 

*** Permission for revised Python logo usage ***
On Fri, Mar 12, 2021 at 4:15 PM M.-A. Lemburg <mal@python.org> wrote:
 Hi Michelle,
 
 I believe your designer just took the logo and changed the color to the dark orange in the diagram and calls this a "knockout". The logo appears unchanged when zooming in, so this is nominative use and permitted.
 
 Many thanks.
 
 Best Regards,
 -- Marc-Andre LemburgPython Software Foundationhttp://www.python.org/psf/http://www.malemburg.com/ 
 
 
 On 12.03.2021 23:02, Michele Chambers wrote:
 Hi Marc - 
 Thanks for the quick response! 
 Here is a draft of a diagram where the logo would be used. Is this an acceptable way to use the logo?  
 Thanks, Michele  
 
 
 On Fri, Mar 12, 2021 at 1:56 PM M.-A. Lemburg <mal@python.org> wrote:
 Hi Michelle,
 
 please send a larger version of the logo and the background you intend to print this on. It is not clear what you mean with "knockout". 
 
 I suppose the designer is referring to adding an extra outset outline to make sure the print comes out fine from the printer (as in e.g. https://support.bookbaby.com/hc/en-us/articles/360034308053-How-to-properly-set-up-knockout-printing), but please advise.
 
 Thanks,
 -- Marc-Andre LemburgPython Software Foundationhttp://www.python.org/psf/http://www.malemburg.com/ 
 
 On 12.03.2021 17:26, Michele Chambers wrote:
 Hello - 
 We are working with a designer on new Dask visuals. In some of the diagrams, the designer has used a knockout of the Python logo as depicted below. I don't see guidelines on knockout version of the logo. Can you advise if this is acceptable? If not, what are the guidelines for knockouts?  
 
 
 _______________________________________________psf-trademarks mailing listpsf-trademarks@python.orgList: https://mail.python.org/mailman/listinfo/psf-trademarks

**Comment by michelechambers** [comment]
Hi Everyone -

The diagrams are completed and I've attached the PNG / GIF versions as a zipfile. Separately there's a PNG of the updated color palette and the Twitter background. There's an index of the library of "assets" - these are icons and the components used to draw the images that could be reused to create new diagrams - that are available in the Figma files (the source files for the diagrams). 

There are "light" and "dark" versions of each diagram. The light is on a white background, and the dark are on a black background. There's only one version of the animation (on white background). 

I have invited @mrocklin and @jacobtomlinson to be editors on the Figma source files. I've added @jrbourbeau as a viewer. I can add others, as appropriate, as editors or viewers. Just let me know what that should be.  

Lastly, I worked with @jacobtomlinson to identify additional assets that would be useful to the community (eg: a full brand guideline like the Jupyter brand guide (https://usermanual.wiki/Pdf/jupyterbrandguide.893400078/view), a website style guide, documentation style guide & Sphinx template, Google presentation template) that we'll work on over the next few months. When I have a draft of those, I'll post to get everyone's feedback. 

Let me know if you have any questions. 

Thanks,
Michele

![Dask color palette](https://user-images.githubusercontent.com/80490707/116123286-74300800-a688-11eb-9aca-76e28905adff.png)
![Dask Twitter header](https://user-images.githubusercontent.com/80490707/116123306-7a25e900-a688-11eb-898b-ef2f0c1a9dac.png)
![Dask Asset Library](https://user-images.githubusercontent.com/80490707/116123329-80b46080-a688-11eb-8f9e-0aad22e93d46.png)
[Dask diagrams Apr 2021.zip](https://github.com/dask/community/files/6378913/Dask.diagrams.Apr.2021.zip)
![Dask animation](https://user-images.githubusercontent.com/80490707/116123364-8a3dc880-a688-11eb-89da-c211d58c4704.gif)

**Comment by GenevieveBuckley** [comment]
Now that we're doing more stuff with HTML representations, I've noticed that some of these brand colours tend to fail accessibility checks on a white/light background. Can we get a review of these colours with that in mind?

I used [this tool](https://webaim.org/resources/contrastchecker/) when I realized I was squinting at stuff a lot more than I should be, but there might be other, better tools around.

For some specific examples: I personally find the blue on blue text/background in the diagrams above pretty challenging to read, and also struggled with the light grey "Neutral/Text" colour with a white background.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @GenevieveBuckley.

cc @michelechambers

**Comment by GenevieveBuckley** [comment]
James made a similar point earlier in the thread, so it's possible some of these conversations are already ongoing & I'm new to the party

> The blue boxes with text might benefit from higher contrast between the text and background color. I don't have strong thoughts on how to do this (e.g. darker text vs. lighter background)

**Comment by michelechambers** [comment]
Thanks for the feedback @GenevieveBuckley. I'll work with the designer to address the accessibility issue and will update here when I have a solution.

**Comment by jacobtomlinson** [comment]
@michelechambers could we get an update on the color accessibility issues? Also we would be keen to have some input from the designer on an extended palette of colors that could be used in other diagrams, just blue and orange is a little constraining.

cc @mrocklin @jrbourbeau

**Comment by jsignell** [comment]
@ncclementi @jacobtomlinson and I were talking about this in our docs meeting. It'd be nice to get these fixed up and the colors checked for accessibility so that we can include them in the docs!

**Comment by michelechambers** [comment]
Hi Everyone -

We just engaged our designer this week to expand the color palette to have lighter and darker colors so that we can create the right contrast to address accessibility. We should have a new color palette and sample of one of the images using the higher contrast back on Monday. We'll add that here and then if that works for everyone, we'll update all the images to use the higher contrast. 

Thanks,
Michele

**Comment by christianacromer** [comment]
Hi All, 

After engaging with our designer, I wanted to share an expanded color palette that addresses accessibility standards:

[Dask-Color-211118 (dragged).pdf](https://github.com/dask/community/files/7571902/Dask-Color-211118.dragged.pdf)

[Dask-Color-211118 (dragged) 2.pdf](https://github.com/dask/community/files/7571903/Dask-Color-211118.dragged.2.pdf)

Here's an example of this color palette applied to an existing graph:

[Dask-Color-211118 (dragged) 3.pdf](https://github.com/dask/community/files/7571907/Dask-Color-211118.dragged.3.pdf)

Thoughts and feedback are welcome and appreciated! cc @michelechambers

**Comment by jacobtomlinson** [comment]
Thanks so much! This looks really great, the expanded palette gives way more flexibility and the accessibility side of things looks good!

I think the primary green is perhaps a little luminescent for my taste, makes my eyes vibrate a bit.

How do other's feel about the colour choices? 

(cc folks I've chatted to about this topic @mrocklin @jrbourbeau @GenevieveBuckley @jsignell @jcrist)

**Comment by jcrist** [comment]
Yeah, the green is a bit glow-in-the-dark-y. The orange + black + luminescent green combo do bring about a halloween + frankenstein vibe to me - whether that's what we're going for or not is up to others.

**Comment by christianacromer** [comment]
Thank you for the comments here! I'll take this feedback back to the designer and update once we have a new iteration.

**Comment by christianacromer** [comment]
Hey all! We received back a color palette with a toned-down, darker green option. Let me know what you think!

![Dask-Color-palettea-jpeg](https://user-images.githubusercontent.com/47429388/144639120-77465f26-68fe-429a-b31e-bbb8810cb07e.jpg)
![Dask-Color-palette-jpeg](https://user-images.githubusercontent.com/47429388/144638916-26450d61-da30-40a6-86ce-eb211ffc984e.jpg)
![Dask-Color-jpeg](https://user-images.githubusercontent.com/47429388/144638579-28244189-0042-4e5c-bdab-baa308f7c6a1.jpg)

**Comment by jacobtomlinson** [comment]
Big +1 from me!

**Comment by jsignell** [comment]
Yeah thanks so much for working on this!

**Comment by jacobtomlinson** [comment]
Now that we have a new working group looking at Dask's visual identity as a whole I'm going to close this out in favour of #220.
