### ISSUE TITLE
Updating Dasks visual identity

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#140]
As nudged by @mrocklin I'm opening this to discuss areas of Dask's visual identity that could do with updating.

Two areas I would like to focus on are the [documentation theme](https://github.com/dask/dask-sphinx-theme) and the [dashboard](https://docs.dask.org/en/latest/diagnostics-distributed.html).

In #135 we already have a proposed new colour palette but it would be great to take this further and define things like fonts. What would be great is a toolkit created by designers for use by the community when creating/updating things. Guidance on fonts, colours, layouts, etc to ensure consistency and pleasurable aesthetics across Dask, but in a way that can be referenced and "tested" (I mean like checklist rather than CI here). 

Given the ad-hoc nature of open source development many folks work independently on things, so having some reference would be useful. For example I would be happy to put effort into both the docs theme and dashboard styling, but it's not a big priority item and I would need to be flexible with fitting it into my schedule. Therefore working closely with a designer is unlikely to be an option.

## Documentation

Dask has great documentation but visually there is a lot of scope for improvement. Comparing it with a project like [SpaCy](https://spacy.io/api/lexeme) gives me a bunch of ideas.

One of the things I particularly like is how they've made use of the horizontal space. The Dask docs only take up about 50% of the width on my monitor. SpaCy uses slightly more than that but they also kick code examples out into a third column on wide monitors.

In terms of content and page elements the Dask docs are almost identical, but areas we could improve are:

- Colours
- Fonts
- Responsiveness
- Code syntax highlighting

## Dashboard

The dashboard is very different from the website and documentation. Most of the visual style is taken from the Bokeh defaults and not altered much at all.

I like that it is visually different from the documentation/website, but it would be nice to have things closer aligned. Fonts, colours, etc. The "info" tab for example is very different to all the other pages and also doesn't have a header. Some pages take up full width (status), others only take up half the page (workers).

I would love to make the Dashboard fit more closely with the Dask branding and have more polish. I'm inspired by dashboard in projects like [Weave Scope](https://www.weave.works/docs/scope/latest/features/) or [Grafana](https://grafana.com/grafana/).

It's also important to be aware that we use Bokeh to build the dashboard because it is a much lower barrier for many contributors than some custom JavaScript based page. But it does somewhat constrain us both in terms of customizability and flexibility.

**Comment by jacobtomlinson** [comment]
Perhaps for the dashboard we also want to make it theme-able to enable closer integration into downstream projects. I thinking RAPIDS, Coiled, Saturn, Sagemaker, AzureML, etc, here.

**Comment by michelechambers** [comment]
Very good info and all the details are hugely helpful @jacobtomlinson. 

I think we can help with some of the heavy lifting to make this a bit easier. Here's a proposal that I'd like to get your feedback on:

1. Brand guideline - We'll work with the designer to create a brand guideline (similar to the Jupyter brand guideline https://usermanual.wiki/Pdf/jupyterbrandguide.893400078/view) that we'll contribute. That will include typography/fonts as well as correct usage of logo along with the color palette. 

2. Documentation - For the documentation, we could create a design, UI component library, and help integrate the design into the documentation theme (https://github.com/dask/dask-sphinx-theme). I can get an estimate on this work and then we'll determine if Coiled wants to fund this work. If we move forward with this effort, we'd post interim deliverables for review/feedback and then turn over the final deliverable so that the documentation can be updated over time. 

3. Dashboards - I don't see a way for us to help with that easily. But perhaps if we help with #1 & 2, this can be addressed sooner.

**Comment by jacobtomlinson** [comment]
Thanks @michelechambers that sounds great.

1. This is exactly the kind of thing I would like. I wonder if this could be taken a little further and mix it with 2 to include some guidelines on what webpages should look like in general.
2. That sounds great!
3. This could be a good test of how well 1 and 2 goes. In theory someone who knows the dashboard code could give it a refresh by following the guidelines and using elements from the website. (@charlesbluca is currently exploring dashboard code so may be interested)

**Comment by mrocklin** [comment]
Having Charles take 1-2 and do 3 sounds like a great fit

**Comment by charlesbluca** [comment]
Happy to take that task on.

**Comment by michelechambers** [comment]
> 1. guidelines on what webpages should look like in general.

@jacobtomlinson can you give me a few general webpages so that the guideline can be sure to address at least those types.

**Comment by jacobtomlinson** [comment]
@michelechambers I think the [documentation](https://docs.dask.org/en/latest/) redesign should set the look for webpages in general.

My thought is there are other pages floating around which do not necessarily look like they are part of Dask. Things like the [dashboard](https://docs.dask.org/en/latest/diagnostics-distributed.html), the [helm repo](https://helm.dask.org/), the [gateway repo](https://dask.org/dask-gateway-helm-repo/), etc.

Anything which isn't a Sphinx site and cannot use the Sphinx theme currently doesn't match the branding of the main website.

I think it would make sense to have two different looks for Dask web pages:
- Officially hosted pages such as the Docs, main website, helm repos, etc.
- Self hosted pages such as the dashboard.

I think user's should be able to tell the difference between "this is part of the Dask website" and "this is something I've launched". But the two looks should tie together. Something like the self hosted pages mainly use the secondary palate and the official pages use the primary pallete but have all the same elements and styles.

Some pages such as the Helm chart repo are created in an ad-hoc fashion by contributors. So having some guidelines and resources that contributors can refer to would help everything feel more connected.

**Comment by GenevieveBuckley** [comment]
Flagging this request for a better architecture diagram for the distributed system here (https://github.com/dask/dask/issues/4471).

Ii don't *think* this has already been done, so perhaps someone here could take that on. Possibly this is within the scope of @michelechambers work? (And if this was done a long time ago, that's great - let me know and I'll close that old issue)

**Comment by GenevieveBuckley** [comment]
Also, this request for flowcharts for Dask introduction docs: https://github.com/dask/dask/issues/5965

**Comment by jacobtomlinson** [comment]
Welcome, great to have you here! The monthly meeting is generally for outward community discussion, this feels like an inward topic so perhaps a separate meeting would make sense.

**Comment by AdiReske** [comment]
Thank you @jacobtomlinson ! That makes sense. How about I just share some analytics from Google analytics about site visits and traffic sources in the past few years. Just a couple of simple slides - 3 mins. Then I can suggest some meeting slots. Does this work? I think there was another thread on GA so that would be useful for the community

**Comment by jacobtomlinson** [comment]
Sounds perfect!

**Comment by jsignell** [comment]
Welcome welcome! Feel free to add me on the invite as well :)

**Comment by GenevieveBuckley** [comment]
Hi @AdiReske, welcome! 👋 
I just started a new job, so I'll be a lot less active. I won't join you all for the meeting.

**Comment by jacobtomlinson** [comment]
Now that we have a new working group looking at Dask's visual identity as a whole I'm going to close this out in favour of https://github.com/dask/community/issues/220.
