### ISSUE TITLE
GPU team

### ISSUE THREAD

**Issue by mrocklin** [dask/community#143]
Hi Folks,

I've made a @dask/gpu team .  So far I've invited some of the RAPIDS folks to that team.  Please engage this issue with a :rocket: emoji if you want to be added.  Let me know if you are on the team currently and want to be removed.

-matt!

**Comment by jakirkham** [comment]
Thanks all! We've added everyone who responded. Some of you are outside the org, so will need to accept the invite to join. This should show up in an email or can visit this link ( https://github.com/orgs/dask/invitation ). For those of you that we missed (and have already checked for an invite), please comment here and we'll add you.
