### ISSUE TITLE
dask-histogram as part of dask-contrib

### ISSUE THREAD

**Issue by douglasdavis** [dask/community#154]
I've been working on [dask-histogram](https://github.com/douglasdavis/dask-histogram) for a little while now and it's "complete" w.r.t. the initial goal (make [boost-histogram](https://github.com/scikit-hep/boost-histogram) Dask collection compatible). It's something I'm happy to continue developing, maintaining, and releasing. @jrbourbeau and I had a quick chat about it potentially being a good project for dask-contrib and I'd be happy for it to live there if there are no objections.

**Comment by jrbourbeau** [comment]
+1 from me. I think `dask-histogram` would make a good contrib project. There's an open PR into `dask` (xref https://github.com/dask/dask/pull/7354) which outlines the criteria for adding a new package to the dask-contrib GitHub org (note that `dask-histogram` meets all the current criteria). Perhaps this will provide good motivation for us to finish up that document and then move `dask-histogram` over.

As a side note, if the goal of `dask-histogram` is to integrate `boost-histogram` with Dask, you might consider seeing if the `boost-histogram` developers have an interest in including the functionality from `dask-histogram` directly in `boost-histogram`. This type of upstreaming has happened before (e.g. with `dask-xgboost` and `dask-lightgbm`) and is likely to increase the visibility of any `boost-histogram` + Dask capabilities for `boost-histogram` users. Though this is totally up to you -- I'm just bringing this up as a suggestion.

**Comment by jakirkham** [comment]
Also +1 from me

**Comment by martindurant** [comment]
I'm sure we have enough votes. @douglasdavis , are you ready to make the move, or are there still conversations elsewhere you wish to clear up first?

**Comment by jakirkham** [comment]
Agreed I think the other question is, how we do the transfer? IOW who has permissions on dask-contrib to facilitate this and what does Doug need to do to make the move

**Comment by martindurant** [comment]
@jrbourbeau , can you make me an admin on dask-contrib so I can do the move? I assume all dask admins should be dask-contrib admins for this kind of thing.

**Comment by jakirkham** [comment]
Agreed would be good to add all admins over there

**Comment by douglasdavis** [comment]
> I'm sure we have enough votes. @douglasdavis , are you ready to make the move, or are there still conversations elsewhere you wish to clear up first?

Just mentioning here that I had a quick chat with Martin confirming I'm ready for it to be moved to dask-contrib, I passed ownership to him in prep for making the move.

**Comment by jrbourbeau** [comment]
I've invited John, Martin, Julia, Ben, and Matt to be admins for `dask-contrib`. If other `dask` org admins would like to be added, just let me know

**Comment by martindurant** [comment]
Thanks! 
Done: https://github.com/dask-contrib/dask-histogram

**Comment by jakirkham** [comment]
Thanks all! 😄
