### ISSUE TITLE
Dask Summit Session Chairs

### ISSUE THREAD

**Issue by mrocklin** [dask/community#156]
Hi folks, 

For the Dask Summit next week we need folks to chair sessions.  This mostly means welcoming folks, announcing speakers, maintaining Zoom, and dealing with any unexpected issues that arise.  Volunteers are welcome to sign up at the following link

https://docs.google.com/spreadsheets/d/123PsClJ5fzkVCLwzbaKquVPwcTJXPu_6v1omstVawLY/edit#gid=2113094062

**Comment by GenevieveBuckley** [comment]
Closing this issue, since I believe we're all set for session chairs now.
