### ISSUE TITLE
Office hours for Dask Q&A with the life science community

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/community#157]
One idea that's sprang out of the life science workshop at the Dask Summit is that it would be good to have 'office hours' for Q&A between a Dask maintainer and people in the life sciences community.

@mrocklin says that he would be happy to volunteer for say, an hour a month. If we can find 2-3 other people who could do this as well, then we could host semi-regular office hours (perhaps, once every fortnight).

@jakirkham and @quasiben, is this something you might be willing to do, too?

Is there anyone else I haven't mentioned yet who also might be interested?

**Comment by GenevieveBuckley** [comment]
I know @martindurant has previously worked in medical imaging research (MRI). Is this something you'd have the interest/availability for, Martin?

**Comment by GenevieveBuckley** [comment]
And @jsignell has a geoscience background, which has a lot more overlap with the needs & interests of people working with bio-image data. Both are often dealing with big arrays and similar challenges due to that. Would you be interested and have time for this, Julia?

**Comment by GenevieveBuckley** [comment]
@jacobtomlinson would you be interested in something like this?

**Comment by jacobtomlinson** [comment]
Sounds good! I can't always make things like this, I've been rubbish with the Dask social things so far. But I'm happy to put my name down and I'll try my best.

**Comment by martindurant** [comment]
I'm not certain how relevant my experience would be, but i'd be happy to help out.

On May 20, 2021 3:19:05 AM EDT, Genevieve Buckley ***@***.***> wrote:
>I know @martindurant has previously worked in medical imaging research
>(MRI). Is this something you'd have the interest/availability for,
>Martin?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/community/issues/157#issuecomment-844786619

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by quasiben** [comment]
I'd be happy to volunteer some time .  Thanks or organizing @GenevieveBuckley !

**Comment by jakirkham** [comment]
Happy to help :)

**Comment by mrocklin** [comment]
My sense is that if we get Ben, John, and maybe Jacob or myself to commit
to once every month then we should reliably be able to support an event
every couple of weeks.  This seems like enough to test this out.

**Comment by GenevieveBuckley** [comment]
Ok, I'm told there's a RAPIDS release next week, so let's start the week after. @quasiben would you be happy to start us off?

We won't have a fixed hour timeslot, instead I'll give everyone a week and you can all choose a time that suits you best that week (or ask to swap weeks, etc). I want to prioritize convenience for you, because it will be sad if people turn up to ask questions and no-one is there to answer them.

**Comment by GenevieveBuckley** [comment]
[Here is the draft schedule](https://docs.google.com/spreadsheets/d/1RYaS39L_ksaecheX6_sGlK02fpuoQhb0hFxwxd-xdxU/edit?usp=sharing)

Please tell me which hour during the week your name is down for suits you best (or tell me if you want to switch weeks). I've made some suggestions for possible times if you want - but I want to know what's the easiest/best for you.

**Comment by quasiben** [comment]
Wed. June 9th at 11 AM EDT/8AM PST/11AM EST works for me.   Thanks @GenevieveBuckley !

**Comment by GenevieveBuckley** [comment]
> Wed. June 9th at 11 AM EDT/8AM PST/11AM EST works for me. Thanks @GenevieveBuckley !

Ok, I'll lock in https://everytimezone.com/s/b0c638c2

**Comment by jsignell** [comment]
I swapped my weeks with @martindurant because I'm on vacation the original week I had :)

**Comment by GenevieveBuckley** [comment]
@jacobtomlinson are you happy with the week 21st - 25th June? Can you pick a 1 hour time slot and tell me when suits you? 

(~2pm BST might give some US east coast folks a chance to join along with Europeans, but you should pick whatever works best for you)

**Comment by jacobtomlinson** [comment]
Ah sorry I'm out on PTO that week.

**Comment by GenevieveBuckley** [comment]
## Update
We've run two "Ask a Maintainer" events now, timed to be relatively accessible for the USA and Europe.
* First event: 1 person attended with questions.
* Second event: I'm told two people entered the chat room briefly but didn't turn on camera/microphone.

### Thoughts & opinions
* Ben: "Happy to do this again – I think it will take a little time to grow"
* Julia: "My only real idea is maybe I could have been working on a PR live and screensharing or something so that there was something for people to just passively watch."
* Genevieve:
	* I'm not sure it will grow with time, my experience with these things is that the first one or two events is usually the biggest.
	* I don't think there are more options to promote this that we aren't already using. For the first event, I emailed people directly, posted reminders in the Slack, and tweeted a whole bunch. For subsequent events, I'm not comfortable emailing people without their explicit consent, which leaves twitter and slack.
	* The live streaming idea is interesting, but it doesn't target the original problem we were trying to solve with this event.

### What do we want to do now?
Our options are:
1. Cancel this experiment due to low attendance, and focus on other ways to support the community
2. Run a few more, and then reassess.
3. ...something else?

I'm leaning towards 1, but happy to hear other opinions. Regardless of what we do here, Matt & I will probably need to chat about what alternatives we can pursue.

**Comment by mrocklin** [comment]
We used to run regular tutorials.  These were well attended.  There has been a desire for more "next level" content.  I wonder if there is a way to promote this kind of activity instead.  This is kind of like @jsignell 's suggestion of live streaming, but maybe with a bit more preparation.

I've thought before about analyzing or optimizing a workload live.  This is a little bit like live streaming, but maybe with user-submitted computations.

**Comment by mrocklin** [comment]
> Cancel this experiment due to low attendance, and focus on other ways to support the community

Also, I think that it's totally ok to wrap up this experiment.  We can only run new experiments if we stop running old ones :)

**Comment by jsignell** [comment]
Yeah I think cancel this experiment and try a new experiment! I really like the idea of optimizing or debugging a workload live. I think that would benefit from a more formal submission process though.

**Comment by GenevieveBuckley** [comment]
Ok then, sounds like a plan.

* We won't do anymore office hours, due to the low attendance.
* In the future, we might experiment with:
    * content on optimizing / debugging workloads
    * more dask tutorials, since those were well attended previously
* We might also consider allocating more of my time towards generating scientific domain specific examples for blogposts, etc. This has been requested a bunch in our survey and community consultation. Generating this content is likely to be time consuming, and useful to a very specific audience, so we'll have to choose the specific examples/domains carefully to get the best bang for our buck.

**Comment by GenevieveBuckley** [comment]
Another idea: bookable time slots.

I was chatting to Juan this evening about the office hours we used to run uni, and our experiment with office hours for Dask. He wonders if maybe bookable time slots would be a more attractive option, which is something he's been trying out recently here: https://twitter.com/jnuneziglesias/status/1385754529639985152

If no one books a spot there's no cost to it, you just have to be very careful about how many bookings you allow and not taking on too much of that person's project in your regular work hours. Some follow up with links & resources is ok (I find I have to be careful about how much outside time I end up spending). So maybe I'll try something like that later on this year, we'll see.
