### ISSUE TITLE
Release 2021.05.1

### ISSUE THREAD

**Issue by quasiben** [dask/community#159]
I recall someone saying that we were planning to release this Friday (05-29-2021), is that correct ?

**Comment by jrbourbeau** [comment]
Yeah, I was planning to open up an issue later today. I'd like to release this Friday if there aren't any blockers

**Comment by mrocklin** [comment]
I believe that @jrbourbeau is planning this, yes.  Thank you for raising
the issue Ben.

**Comment by quasiben** [comment]
Thanks for confirming!

**Comment by jakirkham** [comment]
Should add we are working with dask-geopandas on addressing the issue

**Comment by jakirkham** [comment]
Would it be alright if we start the release in the morning tomorrow?

**Comment by jrbourbeau** [comment]
Yeah, no problem. I can release tomorrow morning my time (central time zone) -- as normal I'll ping this issue before starting to push things out. 

Also, I wanted to flag that we should resolve https://github.com/dask/distributed/pull/4853#issuecomment-849704400 before releasing. FWIW @quasiben and others are working on a fix now

**Comment by jakirkham** [comment]
We're still encountering an issue with the dashboard changes (even with PR https://github.com/dask/distributed/pull/4860 included). Investigating...

cc @dantegd

**Comment by jrbourbeau** [comment]
Alright, thanks for the heads up @jakirkham. If you have a public-facing traceback, CI failure, etc. you could point to, that would be welcome (though no worries if not)

**Comment by jrbourbeau** [comment]
With https://github.com/dask/distributed/pull/4863 merged in to fix the issue @jakirkham was seeing, I'm going to start releasing

**Comment by jrbourbeau** [comment]
Closing as `2021.05.1` is out on PyPI, conda-forge, and Docker Hub. Thanks all!
