### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by mrocklin** [dask/community#164]
Hi All, 

I'd like for us to briefly synchronize on how we want Dask commit messages to look.  

Today we squash-and-merge (which I love for many reasons) but this causes default commit messages to look like the following:

```
commit 0b2053f958a2c222184c78218a87d93f6a82b5d9
Author: Tom White <tom.e.white@gmail.com>
Date:   Wed May 26 17:57:13 2021 +0100

    Implement da.searchsorted (#7696)

    * Implement da.searchsorted

    * Support numpy 1.16: np.expand_dims doesn't take axis tuple

    * Address review feedback from @douglasdavis

    * Simplify expand_dims replacement for multiple new dimensions to avoid loop
 (suggested by @jakirkham).

    * Update dask/array/routines.py

    Co-authored-by: jakirkham <jakirkham@gmail.com>

    * Update dask/array/routines.py

    Co-authored-by: jakirkham <jakirkham@gmail.com>

    * Update dask/array/routines.py

    Co-authored-by: jakirkham <jakirkham@gmail.com>

    Co-authored-by: jakirkham <jakirkham@gmail.com>
```

This message is not super informative.  The bullet points here are mostly noise, which makes our git history somewhat less spectacular than it otherwise could be :) 

Historically when merging PRs I've always removed this noise (unless the PR submitter did a particularly good job with commit messages and rebased) and I either 

1.  Write in my own description
2.  Copy the description that the author provided in the top comment (in the above case it's "This adds a block implementation of np.searchsorted."
3.  Just leave an empty commit message

I find that these are all three pretty cheap options to do and result iin a more presentable repository for others.  Any thoughts?

cc @jrbourbeau @jsignell

**Comment by jakirkham** [comment]
Personally I'm not crazy about this. Though I think I've already expressed this POV when this was raised before. My main gripe is this is just extra cognitive load on people for minimal benefit (anyone can go read the PR if they are interested). Plus it can be difficult to do in some cases (like mobile browsers)

That said, if other people want this, would suggest coming up with a way to automate it. This would allow it to be standardized, keep cognitive load minimal, and work basically everywhere. Maybe something like this ( https://github.com/jetersen/no-merge-description-extension )?

**Comment by mrocklin** [comment]
> Personally I'm not crazy about this. Though I think I've already expressed this POV when this was raised before. My main gripe is this is just extra cognitive load on people for minimal benefit (anyone can go read the PR if they are interested). 

The third option of just removing all of the bullet points can be done in a few seconds.  The second option of copying the authors original post takes less than twenty seconds.  This feels like a very very small cognitive load to me.

> Plus it can be difficult to do in some cases (like mobile browsers)

Personally, I'm not sure I've ever merged a PR from my phone.  Usually I like to take a look through things first and I don't think I've ever used my phone to read diffs.

> That said, if other people want this, would suggest coming up with a way to automate it.

I think that this requires a little bit of human judgement.  I don't think that automation is necessary here.


However, maybe what's happening here is that something that is just very very easy for me to do (look at a commit message, make a decision, and then delete or copy something) is not universally easy.

**Comment by jsignell** [comment]
I'm happy with the approach that Matt outlined. I have never thought about this before since I always rely on going back to merged PRs whenever I need to do some detective work.

I am totally down to have a system!

**Comment by martindurant** [comment]
I agree that the bullets are not (usually) useful, but is a truncated message more useful? Does the extra dross do more than marginally inflate the size of the repo?

**Comment by jrbourbeau** [comment]
Yeah, I'm in favor of slimming down what's recorded in our `git log`. Personally, I've always just deleted commit messages so that PR titles are the only thing that appear in the `git log`.

**Comment by mrocklin** [comment]
> Does the extra dross do more than marginally inflate the size of the repo?

Some people look at `git log` or use `git blame`.  Git messages can add or remove value in these cases.

> dross

Had to look that one up ;)

**Comment by jsignell** [comment]
Just did my first improved merge. It took me 2 minutes and it felt good. :+1:

**Comment by mrocklin** [comment]
```
commit 7af542afaeba9eea46cea653c51a02a2c3376962 (HEAD -> main, dask/main)
Author: Krishan Bhasin <8904718+KrishanBhasin@users.noreply.github.com>
Date:   Fri Jun 11 19:40:11 2021 +0100

    Allow `DataFrame.join()` to take a list of DataFrames to merge with (#7578)
    
    Pairwise approach to merging many (>100) dataframes with each other dataframes together.
    
    The major advantage for this specific use case was that once any given pair of dataframes finished being prepared/computing, their merges could start ahead of time; any dataframes that were slow to materialise don't have to hold up the entire merging process.
```

:+1: 

To @jakirkham 's point.  I also don't mean to make any kind of expecation on folks.  I think it's a nice and stylish thing to do though, and I think that if the few people who merge most of the PRs get into this habit then that solves 95% of the problem from my persepctive.  

Honestly, with @jrbourbeau and @jsignell on board I'm happy :)  Closing.

**Comment by jsignell** [comment]
Lol reading that over I see I did a very mediocre job. But hopefully it's at least kind of legible :roll_eyes:

**Comment by mrocklin** [comment]
Mediocre is great!

**Comment by quasiben** [comment]
Thanks for the ping @mrocklin -- cleaning up the messages seems like a good idea and option 2 looks reasonable

**Comment by jacobtomlinson** [comment]
My preference would be for option 3 to be the default and option 2 if the author included a decent summary.

The only thing I ever want from `git log` or `git blame` is the PR number because so much review and discussion happens on PRs and not much context gets contained in the commit message. 

Happy to be a good citizen though.

**Comment by jsignell** [comment]
Yeah I think 2 or 3 are equally valid and both totally fine.

**Comment by mrocklin** [comment]
Agreed.  I try to do 2 when I can, but am comfortable doing 3.

**Comment by jakirkham** [comment]
Think this may doable via a GitHub setting now. Note this is under ( https://github.com/dask/dask/settings or any repo settings page ) and then one needs to scroll to the bottom for "Pull Requests"

<img width="1840" alt="Screen Shot 2023-01-10 at 10 29 03 PM" src="https://user-images.githubusercontent.com/3019665/211733905-0f9a0f34-3c4f-4095-bb6a-8d78e42163e4.png">
