### ISSUE TITLE
Release (off cycle)

### ISSUE THREAD

**Issue by mrocklin** [dask/community#173]
Hi All, 

There was a stability bug that was recently fixed.  Do we want to do a release this Friday to get this out there?  cc @fjetter @jrbourbeau?

Also cc @quasiben so RAPIDS is in the loop.

**Comment by jakirkham** [comment]
We've already pinned Dask for the upcoming release. So probably won't change that (depending on what bug fix is referred to)

**Comment by quasiben** [comment]
Can you link to the issue ?

**Comment by jrbourbeau** [comment]
https://github.com/dask/distributed/pull/5103

**Comment by jrbourbeau** [comment]
No strong opinion from me either way. I'm happy to push out a release tomorrow if there aren't known blockers (I'm not currently aware of any).

It would be good to get https://github.com/dask/dask/pull/7956 and https://github.com/dask/dask/pull/7939 in before the next release. I'm planning to merge both those PRs shortly. What about https://github.com/dask/distributed/pull/5141? @mrocklin @jakirkham are we comfortable including that too?

**Comment by jakirkham** [comment]
Sure I think we should have some fix for the other side of the OpenSSL bug. Agree Matt's solution seems reasonable

**Comment by jrbourbeau** [comment]
Alright, all the mentioned PRs have been merged. Let's plan to release tomorrow unless any objections arise between now and then. Also cc'ing @jsignell for visibility

**Comment by fjetter** [comment]
There is also https://github.com/dask/distributed/pull/5128 which should be ready to merge and fixes another deadlock

**Comment by jrbourbeau** [comment]
Alright, I'm going to start pushing out the release...

**Comment by jrbourbeau** [comment]
Closing as 2021.07.2 is out. Thanks all!
