### ISSUE TITLE
Stale issue / PR sprint

### ISSUE THREAD

**Issue by jrbourbeau** [dask/community#188]
As discussed in the maintainers meeting today, it's a good time for another stale issue / PR sprint. I'll propose next Thursday, October 14, from 9 AM - 1 PM CT in the Dask whereby channel. This should hopefully provide a large enough windows for folks (both US and Europe based) to come and go as they please / their schedule allows. 

cc @jcrist @ncclementi @jsignell @quasiben @jacobtomlinson @douglasdavis who expressed an interest in the sprint. Does this time window work for you?

**Comment by GenevieveBuckley** [comment]
BTW, I'd also be happy to chip in towards this effort.

My timezone is UTC+11, so that works for a UK/Euro morning, or US folks who might want to have an evening round at it. I get it if that's not convenient for anyone else.

Also, if there's anything asynchronous I can do to help, let me know. Maybe sorting through old issues/PRs and tagging them, so other people can spend more effort on reviewing? I don't currently have permissions to do that now, but I'm sure we could get that worked out if there was a specific task in mind.

**Comment by jrbourbeau** [comment]
+1! @GenevieveBuckley I just added you to the @dask/triage team. You should be able to re-open, close, and label issues/PRs in `dask/dask` and `dask/distributed` now

**Comment by GenevieveBuckley** [comment]
Thanks!
Ok, if I go through old issues/PRs, what do you want me to tag? I could go through and label everything older than a certain date as "stale", but that may or may not be the most helpful thing to do...

**Comment by GenevieveBuckley** [comment]
Ok, I've been working my way backwards from the oldest open issues. I'm up to the start of August 2019.

So far I've:
* Closed 15 issues
* Found 17 more that might be issues we can close. I'll share this list a little later on. Right now I've pinged some of the original authors, so things might change a bit.
* Added good first/second issue to 8 issues, and "needs info" to a few others (not sure how many)

There several places that might be good for easy wins in our sprint:
1. https://github.com/dask/dask/issues/6566 (corresponding issue https://github.com/dask/dask/issues/731) 
2. https://github.com/dask/dask/pull/3630 (corresponding issue https://github.com/dask/dask/issues/2959)
3. https://github.com/dask/dask/pull/8206 (corresponding issue https://github.com/dask/dask/issues/8201)
4. https://github.com/dask/dask/pull/5631 (corresponding issue https://github.com/dask/dask/issues/4275)
5. https://github.com/dask/dask/issues/2568 (this needs a maintainer to do it, someone with permissions to the dask read the docs instance)
6. (Documentation update) https://github.com/dask/dask/issues/4253 
7. (Documentation update) https://github.com/dask/dask/issues/2807#issuecomment-435448751
8. https://github.com/dask/dask/issues/2812

**Comment by GenevieveBuckley** [comment]
Closed another 7 issues today (that's 35 in total :tada:). 

I've finished looking through all the open dask issues. I have not looked at the distributed issues, or the dask or distributed PR backlogs.

Again, I found a bunch more places the maintainer team can look at for easy wins in this stale issue/PR sprint. They are:
14. https://github.com/dask/dask/issues/6768 
15. https://github.com/dask/dask/pull/8259 (corresponding issue https://github.com/dask/dask/issues/6808)
16. https://github.com/dask/dask/issues/7167 
17. https://github.com/dask/dask/pull/7688 (corresponding issue https://github.com/dask/dask/issues/7647) 
18. https://github.com/dask/dask/pull/8138 (it doesn't close the related issue, this is more of an in the meantime, raise and exception situation)

I also have a list of issues that maybe could be closed, but need some kind of discussion or interaction before that happens. Happy to share that too, but I think it makes sense to look at that list of possible easy wins first.
