### ISSUE TITLE
Relax GitHub Actions first time contributor approval

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#191]
A while back GitHub made it so that new contributors cannot trigger GitHub Actions workflows, and a maintainer has to come by and hit "Approve and Run" every time they push a commit to their PR.

Personally I'm finding this very frustrating as it adds friction to reviews.

Today I learned you can make this less strict so it only applied to folks who are brand new to GitHub. I vote we do this. Thoughts?

https://twitter.com/metcalfc/status/1448414192285806592?t=maeChQZTSUh2Ph0YFk-hGA&s=19

**Comment by jrbourbeau** [comment]
No strong opinion from me either. I agree having to approve GHA for each commit to a contributors first PR adds some friction. If nobody objections, I'm inclined to give being less strict a try. @jsignell @fjetter thoughts?

**Comment by digger-yu** [comment]
Hello everyone,

It seems that the poll link provided above is no longer accessible. I would like to share some personal thoughts regarding the pre-defined checklist action that requires manual approval from the maintainer for PR to GitHub. While this may seem more secure, it can be inconvenient from the maintainer's perspective and may defeat the purpose of the action.

To address this issue, I suggest that the switch be turned off by default and be manually turned on and approved by the maintainer if needed. This would prevent unnecessary inconvenience for maintainers who may not know how to turn off the switch.

Overall, I believe this approach would be more user-friendly and efficient. Thank you for considering my suggestions.
