### ISSUE TITLE
Docs sprint 2019-08-07

### ISSUE THREAD

**Issue by mrocklin** [dask/community#2]
@jrbourbeau and @martindurant and I are doing a mini docs sprint this morning.  We have a few topics that we're working on:

- [x] Deploy -> Setup in sphinx theme: https://github.com/dask/dask-sphinx-theme/pull/16
- [x] Avoid distributed docs, or move things over https://github.com/dask/distributed/pull/2936
- [ ] array-foo -> array/foo
- [x] Hide graphs details https://github.com/dask/dask/pull/5241
- [x] Use cases -> stories.dask.org https://github.com/dask/dask/pull/5238 and https://github.com/dask/dask-stories/pull/15
- [x] TOC in Why Dask, so that the full argument is above the fold
- [x] Install, make the text more dense, remove endlines  https://github.com/dask/dask/pull/5243
- [x] Bag overview into toplevel bag page?
- [ ] Client API in futures API
- [ ] Advance Best practices to user interface
- [x] Structure the API list in api.rst  https://github.com/dask/dask/pull/5247
- [x] Move dashboard video above progress bar in distributed diagnostics https://github.com/dask/dask/pull/5239
- [ ] Mention numfocus in funding page
- [x] Internal data ingestion + remote data (cloud storage?) https://github.com/dask/dask/pull/5242
- [ ] Move “ - documentation” links to collection name
- [x] Fix formatting in distributed worker docstring https://github.com/dask/distributed/pull/2939
- [ ] Add env var for setting numba threads to array best practices
- [x] Do we want the “Index” section at the bottom of index.rst? (contains same information as sidebar)
- [ ] Possibly could remove “Where to ask for help“ from dev guidelines
- [ ] Move “Run tests“ outside “Development Environment” section
- [x] ~~Graph typos in high level graph docs~~ https://github.com/dask/dask/pull/5237
- [ ] API docs for `visualize` should be added to “Visualize task graphs”. Currently adds minimal value.
- [x] Should “Distributed Scheduling” in the sidebar just redirect to distributed docs? (just a thought, not sure what’s best here) https://github.com/dask/dask/pull/5248
- [x] “Phases of computation” in “Understanding Performance” page doesn’t need to be itemized https://github.com/dask/dask/pull/5245
- [ ] Should “Phases of computation” be more prominently displayed in the docs?
- [x] Are custom collections still experimental? https://github.com/dask/dask/pull/5236
- [x] In “Best Practices”, not all function signatures link to API docs somewhere (e.g. map_overlap does, but map_blocks doesn’t) https://github.com/dask/dask/pull/5246
- [ ] Should “Comparison to Spark“ be higher up on the sidebar? I get asked about this a lot at talks. (not sure the answer should be “yes”, just thinking about it)
- [x] The spark comparison docs might benefit from “Do”/“Don’t”-style side-by-side comparison re: delayed best practices https://github.com/dask/dask/pull/5249

**Comment by mrocklin** [comment]
We've finished for the day.  Next we should probably elevate any larger issues from the list above, and then close this out.

**Comment by GenevieveBuckley** [comment]
This issue is fairly old, should it be closed now?
