### ISSUE TITLE
Pull Request Sprint

### ISSUE THREAD

**Issue by quasiben** [dask/community#20]
At the weekly dask meeting it was suggested that we hold another cleanup sprint -- this time focused around cleaning/commenting/merging outstanding PRs in the dask repos.  This issue is to coordinate the activity and invite others who may want to join.

I'll start off by suggesting the following times I know work for me:

Wednesday 9-5 EST
Thursday 9-4 EST
Friday 1-4 EST

cc @mrocklin

**Comment by mrocklin** [comment]
Those times all mostly work for me.  I'll have to jump out for a meeting or two.  I'll arbitrarily suggest Thursday sometiime after the monthly meeting.

**Comment by jrbourbeau** [comment]
Thursday after the monthly meeting works for me (thanks for coordinating @quasiben)

**Comment by jrbourbeau** [comment]
Thanks @mrocklin @quasiben! I enjoyed this and it was nice to put a dent in the PR backlog : )
