### ISSUE TITLE
Packages on PyPI with sole maintainers

### ISSUE THREAD

**Issue by mmccarty** [dask/community#219]
The following packages in the Dask org have sole maintainers on PyPI:

- [dask-glm](https://pypi.org/project/dask-glm/)
- [dask-gateway](https://pypi.org/project/dask-gateway/)
- [dask-drma](https://pypi.org/project/dask-drmaa/)
- [dask-searchcv](https://pypi.org/project/dask-searchcv/)

I'm not sure if any of these are active (apart from Dask Gateway), but I thought I would list them anyway.

**Comment by jacobtomlinson** [comment]
`dask-drmaa` and `dask-searchcv` are both archived on GitHub, so probably not a huge issue.

`dask-glm` and `dask-gateway` are not though so I would suggest we need to add more (all?) of the core maintainer team to these in order to reduce the bus factor.

Thanks for looking into this @mmccarty

**Comment by jacobtomlinson** [comment]
cc @TomAugspurger and @jcrist

**Comment by TomAugspurger** [comment]
dask-glm can be archived.

**Comment by jakirkham** [comment]
It is worth noting that we have added some non-`core` devs as maintainers of some packages. So it doesn't need to be a `core` member (though that is always an option)

**Comment by jacobtomlinson** [comment]
Absolutely agree about adding non-core folks. However I think it is good to have reasonable core coverage as we are the ones who are typically funded to step in and fix things in a pinch.

**Comment by jrbourbeau** [comment]
Thanks for helping increase the bus factor @mmccarty : ) It sounds like the only project of concern is `dask-gateway` (given the others either already are, or can be, archived). I see there's an issue over in `dask-gateway` about releasing https://github.com/dask/dask-gateway/issues/381 -- should we close this issue and continue the `dask-gateway`-specific conversation over there?

**Comment by mmccarty** [comment]
Thanks all! Closing this issue.
