### ISSUE TITLE
Pushing monthly meeting to March 10?

### ISSUE THREAD

**Issue by jakirkham** [dask/community#227]
As several of us are going to be out on holiday March 3-4 am wondering, could we push the monthly meeting a week? Would propose same day of week and time, but push one week to March 10. Thoughts?

**Comment by jakirkham** [comment]
Adding a few people to get feedback here

cc @jrbourbeau @jsignell @jacobtomlinson @quasiben @mrocklin

**Comment by jsignell** [comment]
I'm fine with either date, but I suspect they are not the same for @jrbourbeau :) 

I would prefer to just keep the meeting when it is and people who are out can assign someone to report for them or just writing things up in the meeting agenda.

**Comment by jakirkham** [comment]
Right the issue is all NVIDIAns will be out. So I don't think we have someone that can stand in our place as it were.

**Comment by jakirkham** [comment]
I suppose an alternative is to schedule a separate meeting for anything that needs someone from NVIDIA to follow up on and defer those items for that separate meeting

**Comment by jrbourbeau** [comment]
> all NVIDIAns will be out

That's great...I hope you all enjoy the time off : )

I'd also prefer to keep the existing date on the calendar. People's calendars tend to fill up for off weeks. Perhaps NVIDIA folks can fill out the brief updates section in the meeting notes and we can still go through them during the regular meeting time (e.g. I can read through them) if there's a status update that they'd like to share with the broader group. 

There is one larger agenda item around dropping/keeping the Cythonized scheduler that NVIDIA folks (in particular @jakirkham) should probably be around for. My sense is this agenda item could be pushed back one monthly meeting (i.e. to the first week of April) without causing much friction. Thoughts?

**Comment by jakirkham** [comment]
Thanks James 😄

Understandable. Generally this sounds ok to me. @charlesbluca @eriknw @jacobtomlinson @madsbk @pentschev @rjzamora @quasiben @mmccarty, thoughts on including a short summary of relevant items in the Dask Monthly meeting notes? 🙂

Am ok with pushing the Cythonized Scheduler item to the next monthly meeting if others are. Should be able to include a summary of what has been done so far in the notes as well.

**Comment by quasiben** [comment]
I'll be in attendance and would be happy to represent NVIDIA folks and their ongoings in Dask land

**Comment by mmccarty** [comment]
I'll be attending as well. 😊

**Comment by jsignell** [comment]
Alright, sounds like we will proceed as usual.
