### ISSUE TITLE
Release tomorrow

### ISSUE THREAD

**Issue by mrocklin** [dask/community#239]
We've cleaned up some deadlocks.  I'd like to release tomorrow.

**Comment by mrocklin** [comment]
@jrbourbeau are you around to help with this?  Everything on my end is good except for https://github.com/dask/distributed/pull/6123 , which I plan to merge a bit later this morning.

**Comment by jrbourbeau** [comment]
Yep, I'm around to help. I've been focusing on other things the past few days, so am not caught up on the recent changes in `distributed`. With a bunch of stuff getting merged recently and https://github.com/dask/distributed/pull/6123 getting in today, are you confident enough in the changes being made that we don't need time to simmer in `main`? 

On the `dask/dask` side of things, we should be good to release. I see @jakirkham gave this issue a 👍 , so I'm assuming RAPIDS folks are okay with releasing (feel free to let us know if that's not the case )

**Comment by mrocklin** [comment]
In these specific changes, yes.  I'll also happy to volunteer to be around this weekend and watch things just in case.

**Comment by jsignell** [comment]
There is nothing blocking on dask/dask AFAICT so i am :+1:

**Comment by jakirkham** [comment]
> Yep, I'm around to help. I've been focusing on other things the past few days, so am not caught up on the recent changes in `distributed`. With a bunch of stuff getting merged recently and [dask/distributed#6123](https://github.com/dask/distributed/pull/6123) getting in today, are you confident enough in the changes being made that we don't need time to simmer in `main`?
> 
> On the `dask/dask` side of things, we should be good to release (cc @jsignell for visibility). I see @jakirkham gave this issue a 👍 , so I'm assuming RAPIDS folks are okay with releasing (feel free to let us know if that's not the case )

Yep +1 on releasing

**Comment by jrbourbeau** [comment]
With https://github.com/dask/distributed/pull/6123 in, I'm going to start pushing things out

**Comment by jrbourbeau** [comment]
On PyPI now 🚀

**Comment by mrocklin** [comment]
Woo!

**Comment by jrbourbeau** [comment]
And the conda packages / docker images are out now too. Thanks all

**Comment by mrocklin** [comment]
Woot.  Thanks James
