### ISSUE TITLE
Release process - Announcement and documentation

### ISSUE THREAD

**Issue by fjetter** [dask/community#247]
Over the past couple of weeks we had a few failed attempts to release, see https://github.com/dask/community/issues/245

While the issue is not very long and it is OK to read ~10-15 comments, it is not absolutely clear what the current state is, what decisions have been made, what's blocking a release, who takes care of resolving the release blockers, who will be the release manager, etc.

I would like to propose that we structure the release announcements a bit better and keep the top-level comment up to date with the most recent information, e.g.

----
Example for a release on-time

|  |  |
| --- | --- |
| Release number | 2022.05.01 |
| Planned release date | 2022-05-12 |
| Status | On-track |
| Release manager | <Who takes care of this release> |

Best effort
- [ ] A ticket we try to close before the release but it will not block the release

Blocker
- [ ] Already known ticket that would cause us to block and postpone the release if not fixed by then

---

With blocker

|  |  |
| --- | --- |
| Release number | 2022.05.01 |
| Planned release date | 2022-05-26 |
| Status | Blocked |
| Release manager | <Who takes care of this release> |

Blockers

# We should assign someone to blockers to have a person responsible for it

- [ ] https://github.com/dask/distributed/issues/6407 
- [ ] https://github.com/dask/distributed/pull/6363#pullrequestreview-980540137 (This should be a new, open ticket)

----

We can open these kind of templates early on and update the tickets with up-to-date information along the way. If potential blockers for a release come up during development, we can track this here already. This could help us with the many "last-minute" cancellations.

Thoughts?

**Comment by jakirkham** [comment]
Generally seems reasonable

If we are going to go with this template (or other similar template), would suggest we add it to the GitHub issue templates of this repo to ease creation

Would be curious to here @jrbourbeau's thoughts here 🙂

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @fjetter. This seems like a reasonable thing to try to me. Judging from the number of 👍 on your original post, it seems that others agree too 

> If we are going to go with this template (or other similar template), would suggest we add it to the GitHub issue templates of this repo to ease creation

I was thinking the same thing -- I'll push up a PR to add a template
