### ISSUE TITLE
Drop zero-padding in release version?

### ISSUE THREAD

**Issue by jrbourbeau** [dask/community#249]
In https://github.com/dask/community/issues/100 we converged on a `YYYY.MM.X` calver version format. In particular, we decided to zero pad the month (i.e. use `2022.05.1` instead of `2022.5.1`) so that string sorting versions works properly.

However, [modern Python version handling normalizes zero padding away](https://github.com/dask/community/issues/100#issuecomment-704468187) so when you, for example, go to PyPI / conda-forge you'll see versions displayed without zero padding https://pypi.org/project/dask/2022.5.1. To my knowledge, this hasn't been a big issue for common Python systems like PyPI/conda-forge, but @jacobtomlinson brought up in a recent monthly community meeting that this zero padding can be problematic for other systems. Specifically, https://github.com/dask/dask-gateway/pull/467 ran into zero padding being problematic for publishing Helm charts. 

I'm opening this issue to gather feedback on whether we want to drop zero-padding in our version convention. FWIW my personal opinion is that, while string sorting is nice to have, things like publishing Helm charts (and maybe other systems as well) seem more important to account for. Additionally, even though PyPI/conda-forge treat `2022.05.1` / `2022.5.1` the same, this small discrepancy can still lead to occasional user confusion (xref https://github.com/dask/distributed/issues/6432). Because of this, I'm in favor of dropping zero-padding. 

cc @jsignell @jacobtomlinson @jakirkham @quasiben @mrocklin @martindurant @fjetter

**Comment by jacobtomlinson** [comment]
> while string sorting is probably more correct with a leading zero, its not perfect still.

This is another compelling point. I occasionally fall into the trap of using string sorting but it can lead to unexpected results with pre-releases. It happens very rarely but can be a time suck to resolve.

**Comment by jakirkham** [comment]
Think I +1'd this in the meeting. So just reiterating that here

Wouldn't worry that much about `str` comparison. The cases where that comes up are typically pretty crude (one off scripts or on the fly usage). There are plenty of libraries and tools (like `importlib_metadata`), which can handle this for users in a smarter way and are easy to pull in. Solvers know how to do this kind of normalization (and if not it is likely a bug).

**Comment by consideRatio** [comment]
Ah one additional note btw, if we use `2022.5.1` etc instead of `2022.05.1`, you suddenly can use various libraries to compare semver versions as 2022.5.1 is a valid semver version where 2022.05.1 isn't.

**Comment by jakirkham** [comment]
What library? Seems like an issue should be raised

**Comment by jrbourbeau** [comment]
Thanks for the feedback all! It sounds like there's pretty solid interest in removing zero-padding. I'll leave this issue open for bit longer to give folks like @jsignell @fjetter, who are currently out on PTO, to weigh in.

**Comment by consideRatio** [comment]
> What library? Seems like an issue should be raised

`2022.05.5` is not a valid semver version, so a library that refutes the version instead of helping out with a sorting operation actually makes sense. I think this was a golang library.

**Comment by jakirkham** [comment]
If this is limited to Go and Go enforces hard semver (like as a language requirement), then yeah that makes sense

Generally multilingual tools (OS package managers, users space installers, etc.) don't have the luxury of saying what is acceptable version. There are some things out there that not only violate SemVer, but go a bit beyond that (use of [letters]( https://wiki.openssl.org/index.php/Versioning ), [odd/even for unstable/stable]( https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases ), etc.). So restricting to SemVer is not practical in the wider world of software hence tooling tends to handle these differences

**Comment by jrbourbeau** [comment]
I'm going to say lazy consensus has been reached here and will start dropping zero-padding in the upcoming 2022.6.0 release https://github.com/dask/community/issues/252

**Comment by jsignell** [comment]
Yeah I am totally fine with dropping the zero padding.

**Comment by jakirkham** [comment]
Sounds good. Closing then
