### ISSUE TITLE
December 2019 Meeting Today

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#25]
As a reminder, the regular monthly meeting is scheduled for today, December 5th at 11:00 US Central / 17:00 UTC. Use https://zoom.us/j/802251830 to join the call.

Topics can be added to the agenda at https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit.

**Comment by jakirkham** [comment]
Do we have a link to the calendar invite? I think my calendar got messed up. So would like to readd it.

**Comment by jacobtomlinson** [comment]
https://calendar.google.com/calendar/embed?src=4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com

**Comment by jakirkham** [comment]
Thanks Jacob! 😄

**Comment by jakirkham** [comment]
Closing as the meeting has passed.
