### ISSUE TITLE
CZI EOSS Proposal

### ISSUE THREAD

**Issue by mrocklin** [dask/community#26]
CZI provides up to $250k in funding for open source projects that are used in the biomedical and health sciences through their Essential Open Source Software for Science program.

https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/

I believe that we can write a strong proposal.

What do we want to propose?  How would we want to use this money if it was granted?

**Comment by mrocklin** [comment]
I propose that we propose the creation of a full time custodian position, whose job it is to watch all of the issue trackers, handle questions, fix bugs as they come in, and identify and implement systemic fixes as necessary.

**Comment by TomAugspurger** [comment]
In case it's useful, pandas' proposal is at https://github.com/TomAugspurger/pandas-czi/blob/master/proposal.pdf. We requested $250,000, and were funded for $200,000.

**Comment by jrbourbeau** [comment]
Also for reference, NumPy's proposal is at https://figshare.com/articles/Proposal_NumPy_OpenBLAS_for_Chan_Zuckerberg_Initiative_EOSS_2019_round_1/10302167

**Comment by mrocklin** [comment]
OK, things are mostly done.  There are two outstanding issues:

1.  We still don't have anything for the diversity statement (see #30)

2.  Are people ok with this budget?:

Salary for Dask fellowship: $200k
Travel budget for conferences: $20k (for the fellow, or others who that fellow supports)
Equipment: $3k (maximum for a MBP I suppose)
NumFOCUS overhead: $22300 (10%)

Total: $245 300

**Comment by datametrician** [comment]
Very minor budget question, but I think the numfocus overhead be of the total... e.g. ~24.5K? I'm not an expert on these things but should we divide 223 by .9 to get the total? So 248K is the total, 24.8 to numfocus, which leaves ~223K.

**Comment by mrocklin** [comment]
OK.  This is submitted.  Thanks everyone for feedback.
