### ISSUE TITLE
Dask Newsletter?

### ISSUE THREAD

**Issue by LilyMelnyk** [dask/community#264]
Hello, Dask community! @adireske, @mrocklin, and I have been having conversations about a potential Dask Newsletter. 

We've got a web form on the new dask.org site where folks can sign-up for a newsletter but, we aren't yet sending one out. 

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/94075152/182227195-9213ab7e-9937-4e3a-bdbd-80e732d0aa04.png">

Currently, we have less than 20 people on the sign-up list (so far).

We wanted to open an issue to get folks' thoughts on this - how do you feel about us launching a (perhaps monthly?) newsletter? Should we do it?

**Comment by jakirkham** [comment]
Who is planning to update the newsletter? What content would be in the newsletter? Also how would this process differ from say including a blurb in the NumFOCUS newsletter (something we also can do and don't do AFAIK)?

**Comment by GenevieveBuckley** [comment]
John makes some good points. Dask doesn't seem to saturate the current channels available to it (eg: struggling to find blog content, not using the current NumFOCUS newsletter much). 

If this is happening just to get a name & logo in front of people's faces frequently, people can kinda tell. Less frequent but high value every time is better than frequent but inconsistent quality.

That said, the Coiled newsletter does a "Dask roundup" column every so often, and I quite like those. The caveat is: I was actively working on Dask as a developer at the time, which might not be the target audience you're thinking of for this.

Stuff that would be high value in a newsletter is when I learn something new. It may also be time-sensitive.
For me, that would include notifications about:
* upcoming Dask online trainings (but like, not a paid commercial training run by a company. Possibly if the event was free, but run by a company I would mind less?)
* upcoming conferences with confirmed speakers on Dask (even better if you can say it'll be up online after the conference)
* new content available online
  * youtube videos of those conference talks up online
  * community created content, where someone's done a cool thing with Dask (could highlight some of those twitter threads)
  * new blogposts up on https://blog.dask.org

Lower value stuff (to me, at least):
* new Dask releases (unless there is some killer new feature, new releases are frequent enough that it's not super valuable information to know there's a new one)
* lists of small to medium bugfixes and improvements that go with each new release

Would you really have a lot of the high value stuff to say every month?

**Comment by GenevieveBuckley** [comment]
I think the two important questions here are: 
1. Who is the newsletter for? 
    - Casual users who want to know more about Dask?
    - People who use Dask at their org right now but are always on the lookout for how to do things better?
    - Developers who want to know about every little pull request (surely not, I imagine those people are already better served by following github issues)
2. How to make sure this thing does not become dominated by content from any one particular company.

**Comment by AdiReske** [comment]
@GenevieveBuckley you're spot on. When the website working group decided to include the newsletter idea, it was exactly about doing a monthly roundups of events, tutorials etc. My team will own it operationally and we will be curating this content from the various channels. I'm happy to share the content for the first newsletter here and if everyone is happy with that, we will use it as a template. Make sense?

**Comment by jacobtomlinson** [comment]
Closing in favour of #291
