### ISSUE TITLE
PyData Global (virtual) - Tutorial proposal

### ISSUE THREAD

**Issue by ncclementi** [dask/community#273]
We chatted in the dask monthly meeting that it would be nice to present the dask tutorial at the PyData Global conference. The tutorials at pydata are 90min so we will have to scale back material, but this shouldn't require much work. 

People interested in this, please join the `dev-tutorial` slack channel. 

Action Items. 
- [ ] Submit proposal (deadline 09/12)
- [ ] If accepted put together material

**Comment by pavithraes** [comment]
Proposal submitted!

**Comment by ncclementi** [comment]
Closing, as this was rejected.
