### ISSUE TITLE
Monthly Community Meeting

### ISSUE THREAD

**Issue by mrocklin** [dask/community#28]
As a reminder, the Monthly Dask Community meeting is this coming Thursday, 2020-01-02

- [Agenda](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit#)
-  [Calendar information](https://docs.dask.org/en/latest/support.html)

**Comment by mrocklin** [comment]
Attendance was low, we suspect due to the holidays.  We've decided to postpone this one week.

@TomAugspurger is it easy for you to modify the calendar for this month?

**Comment by TomAugspurger** [comment]
Done.

**Comment by mrocklin** [comment]
Thanks Tom!

**Comment by datametrician** [comment]
@mrocklin Is the meeting Noon EST or 11AM EST? I joined but no one was on.

**Comment by mrocklin** [comment]
The ground truth for the time is the calendar event listed here: https://docs.dask.org/en/latest/support.html

We generally meet at 11am US Eastern.  It used to be at noon but we changed in I think one or two meetings ago.  This wasn't updated on the agenda document until today unfortunatley.

Anyway, we're meeting in one week anyway, so we have another shot at this.

**Comment by datametrician** [comment]
Weird, I thought I downloaded the calendar invite 2 weeks ago, but I may have deleted the wrong series off my calendar and kept the old one. 2020 is starting off well for me :)

**Comment by jrbourbeau** [comment]
Closing as this month's meeting has past. See you all next month!
