### ISSUE TITLE
Monthly Demo Day

### ISSUE THREAD

**Issue by mrocklin** [dask/community#280]
Hi All, 

During this month's community meeting we discussed ways to improve the current monthly meeting. ([notes here](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit#heading=h.6rj6ivah1vix).) A few common themes arose of that discussion.  

-  People like the current update structure of the current meeting
- Folks would welcome a way to engage a larger group
- If we want to engage them we'll probably want to talk about something less nitty-gritty and also advertise the meeting better
- Demo days (Anaconda has Demo Fridays, NVIDIA Demo Wednesdays) seem good.  Maybe that?

With that in mind I propose that we organize Demo Thursdays, which are at the same time as the community meeting, but two weeks later on.  We can solicit some presentations during the community meeting, refine them over a couple of weeks, and advertise on social-media.  I propose that demos be 5-15m, aiming for 10m as a sweet spot.  

I'm happy to wrangle this for the first few months.  If it works out then I'll probably want to spin it out to someone else (if folks are interested).  

I welcome all comments on this issue, but particularly comments of the following forms:

1.  This is a terrible idea!  What if we did X instead?
2. This is a wonderful idea!  What if we made it even better with Y?
3. Sounds ok.  I've got a presentation.  How about Z?

**Comment by mrocklin** [comment]
First demo day would be not this Thursday, but the Thursday roughly ten days from today.

**Comment by jacobtomlinson** [comment]
I can do a Dask Kubernetes Operator demo.

Should we record these? Summarise them as on blog.dask.org? Both?

**Comment by mrocklin** [comment]
Recording and publishing to YouTube is easy.  I'm not volunteering to blog about them, I welcome others to do so.

**Comment by mrocklin** [comment]
Issue for the first one is up here https://github.com/dask/community/issues/282

I'm aiming for next week (slightly later than planned) to give a bit more time for the first one.

**Comment by mrocklin** [comment]
Does anyone have recommendations on how to make a persistent reminder to folks?  

I wonder if better management of the Dask community calendar would work well.  Do people subscribe to it?  Maybe we could make that easier.

**Comment by mrocklin** [comment]
Thanks all who participating for making this a success.  Closing.

**Comment by mrocklin** [comment]
Ah wait!  No. I wanted to leave this one open and close the other ..

**Comment by jakirkham** [comment]
> Does anyone have recommendations on how to make a persistent reminder to folks?

One can [pin the issue]( https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository )

**Comment by mrocklin** [comment]
Hrm, it appears that the "third thursday of the month" conflicts with the Social Hour.  

@jrbourbeau do you go to this.  Is it populated?  Should I move Demo Day or conflict with it?

**Comment by mrocklin** [comment]
Regardless, for this month I think I'm going to conflict (already scheduled a bit)

**Comment by jrbourbeau** [comment]
I haven't been attending. IIUC I think it's currently not in use. @ncclementi do you know if that's the case? If so, I'll suggest we remove it

**Comment by ncclementi** [comment]
I don't think so, but I also stopped attending a while back because no one would show up. I think we are safe to remove it

**Comment by ncclementi** [comment]
Closing this issue as the demo day's are up and running
