### ISSUE TITLE
Monthly meeting today 

### ISSUE THREAD

**Issue by mrocklin** [dask/community#285]
As a reminder we'll have our monthly today, Thursday, November 3rd, at 10am US Central time

-  [Video Invite](https://us06web.zoom.us/j/87619866741?pwd=S2RxMlRKcnVvakt4NHZoS1cwOGZoZz09)
- [Agenda](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit)

More details [here](https://docs.dask.org/en/latest/support.html). 

Also a reminder that this is that strange week in the year when EU and North American timezones have some shear.  I recommend verifying the time and not trusting locally made calendar events.

**Comment by jacobtomlinson** [comment]
Daylight savings offset week is always a joy! Given that this meeting is anchored in US Central, this meeting will be an hour earlier than usual for European folks.

For me, in the UK it will be 3pm GMT, and for Europeans on CET, it will be 4pm.
