### ISSUE TITLE
November Demo Day 2022-11-17

### ISSUE THREAD

**Issue by mrocklin** [dask/community#286]
[Zoom Meeting Invite](https://www.google.com/url?q=https://us06web.zoom.us/j/89383035703?pwd%3DWkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09&sa=D&source=calendar&usd=2&usg=AOvVaw1GbPhE5xfqMKxyam1Ml-Qd) 

https://github.com/dask/community/issues/280

Our last demo day was a great success #282 !  https://youtu.be/VlTgcLqb1DQ 

If anything, presentations were *too good*.  This time we'd like to lower the bar and make things more casual.  Can anyone help?  

## When

Thursday, November 17th, at 10am US Central time (meeting invite will be posted here later)

## Context

I'd like to solicit 5-10 minute demos that show off ongoing or lesser known work.  I hope to have 3-5 of these during the meeting.  Meetings will be recorded and advertised on social.  Hopefully this helps to educate folks on some of the great work people are up to.

If you're interested please respond to this issue with a brief (a couple sentences) description.  If you have colleagues who you think should be interested please let them know.

## Agenda

- 2,000,000,000 lightning flashes: @ktyle 
- Dask CLI: @douglasdavis 
- Optuna: @jrbourbeau 
- Community Interlude: @mrocklin 
- Dask Awkward: @douglasdavis 
- PySpy: @gjoseph92 

## Meeting Invite

Topic: Dask Demo Day
Time: Nov 17, 2022 08:00 AM Pacific Time (US and Canada)
        Every month on the Third Thu, until May 21, 2026, 43 occurrence(s)

Please download and import the following iCalendar (.ics) files to your calendar system.
Monthly: [https://us06web.zoom.us/meeting/tZ0uf-qorT4tGtc673iGO0K1lLAN0XrtJ7DV/ics?icsToken=98tyKuGhrTMpGteQtxmERpx5A4qgb_TztiVajbdeyki2Cgd8MiinOs5jHOJHAsz6](https://www.google.com/url?q=https://us06web.zoom.us/meeting/tZ0uf-qorT4tGtc673iGO0K1lLAN0XrtJ7DV/ics?icsToken%3D98tyKuGhrTMpGteQtxmERpx5A4qgb_TztiVajbdeyki2Cgd8MiinOs5jHOJHAsz6&sa=D&source=calendar&usd=2&usg=AOvVaw0OMk88j5yqFaQyHRNmitIp)

Join Zoom Meeting
[https://us06web.zoom.us/j/89383035703?pwd=WkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09](https://www.google.com/url?q=https://us06web.zoom.us/j/89383035703?pwd%3DWkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09&sa=D&source=calendar&usd=2&usg=AOvVaw1GbPhE5xfqMKxyam1Ml-Qd)

Meeting ID: 893 8303 5703
Passcode: 130458
One tap mobile
+13462487799,,89383035703# US (Houston)
+16694449171,,89383035703# US

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 669 444 9171 US
        +1 669 900 6833 US (San Jose)
        +1 719 359 4580 US
        +1 253 205 0468 US
        +1 253 215 8782 US (Tacoma)
        +1 507 473 4847 US
        +1 564 217 2000 US
        +1 646 931 3860 US
        +1 689 278 1000 US
        +1 929 436 2866 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 305 224 1968 US
        +1 309 205 3325 US
        +1 312 626 6799 US (Chicago)
        +1 360 209 5623 US
        +1 386 347 5053 US
Meeting ID: 893 8303 5703
Find your local number: [https://us06web.zoom.us/u/kcspFo8Sig](https://www.google.com/url?q=https://us06web.zoom.us/u/kcspFo8Sig&sa=D&source=calendar&usd=2&usg=AOvVaw2YWRtQlAJPjagDlGxD8iQk)

**Comment by gjoseph92** [comment]
Sure, I could talk about https://github.com/gjoseph92/dask-pyspy

**Comment by mrocklin** [comment]
Added you to the list!

**Comment by ktyle** [comment]
I can present on visualizing a 8-year 2-billion + row dataframe of lightning flashes over the US with CUDA/RAPIDS-AI/Dask/Datashader, thanks to a lot of en(light)e(ning) help from @bdice and @rjzamora!

**Comment by mrocklin** [comment]
You're on the schedule.  I'm looking forward to it @ktyle !

**Comment by gjoseph92** [comment]
@TomAugspurger maybe?

**Comment by mrocklin** [comment]
Reminder that we're on for this week.  Verifying, @ktyle @gjoseph92 @douglasdavis @jacobtomlinson you all are still on for Thursday?

**Comment by ktyle** [comment]
yep!

**Comment by douglasdavis** [comment]
:+1:

**Comment by jrbourbeau** [comment]
Native integration with Dask was just added to Optuna. I'm happy to give a demo if there's time

**Comment by mrocklin** [comment]
Cool.  I'll add you at the end.

**Comment by mrocklin** [comment]
I've updated the original comment with Zoom meeting invite details.  I've also made this recurring so that it should be the same going forwards.  I'm also editing the [Dask Google Calendar](https://calendar.google.com/calendar/u/0?cid=NGwwdnRzMGMxY2dkYnE1amhjb2dqNTVzZnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) to have a recurring event there.

[https://us06web.zoom.us/j/89383035703?pwd=WkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09](https://www.google.com/url?q=https://us06web.zoom.us/j/89383035703?pwd%3DWkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09&sa=D&source=calendar&usd=2&usg=AOvVaw1GbPhE5xfqMKxyam1Ml-Qd)

**Comment by mrocklin** [comment]
Tweet scheduled to go out tomorrow morning to advertise and then Thursday morning an hour before the meeting.

**Comment by mrocklin** [comment]
https://twitter.com/dask_dev/status/1592862297256402945

**Comment by mrocklin** [comment]
Video is up here: https://youtu.be/_x7oaSEJDjA

@rrpelgrim how long do you think it would take you to repurpose this into a blogpost for blog.dask.org.  Worth doing?

**Comment by mrocklin** [comment]
> Worth doing?

Mostly I mean to ask "is this the kind of content that we think would be of value?"  I know that historically we've pushed out a lot of stuff on Coiled that seemed like it would be interesting, but ultimately wasn't.  I'd love your critical point of view here.

**Comment by avriiil** [comment]
There's some excellent content here that we should definitely repurpose. A single blog summarising all the demos doesn't make much sense from an SEO perspective but it may get some traffic by publishing on social channels. It's a relatively quick exercise (1-2 hours) so worth a shot and then we can reevaluate for next month. 

Additionally I think we should these two things which I think will have more impact:

1. create 30s video snippets of each demo and push those to social channels with a link to the full YT rec. That gives us a week of meaningful social content (1 a day). @mrdanjlund77 can you run with this? 
2. potentially more involved: create a `dask/demo-day` repository and have folks upload their demo notebooks there and link to the repo in the YT recording description. This will give folks a chance to try stuff out themselves. This will also become an impressive log of Dask development as we have more and more Demo Days accumulate. Caveat: this obviously depends on folks who gave the demos feeling comfortable sharing those notebooks. How do folks feel about this? @jrbourbeau @ktyle @douglasdavis @gjoseph92

**Comment by douglasdavis** [comment]
for point (2): In general I don't have a strong opinion on this and I would be happy to have what I put together in some repo (especially because it's already reproducible by anyone who watches the video). But if the repo is created, I think we should have a clear note in the README about the casualness/low-bar of demo day, so it's possible for any of the notebooks to be relatively rough (or maybe not work out-of-the-box) in comparison to a lot of advertised notebooks that are uploaded to official project channels. (I know a lot of folk's personal accounts are filled with rough notebooks, but people might have higher expectations for notebooks hosted by a project). I really like the theme of demo day being unpolished!

**Comment by ktyle** [comment]
Would love to not only share the notebook but do so in a reproducible manner ... but the NLDN dataset is proprietary. I could see a scenario where a small subset could be shared, but that makes the necessity of a distributed Dask workflow less apparent.

**Comment by mrocklin** [comment]
My guess is that trying to get people to give actual examples that run is
going to be non-trivial ongoing maintenance work.  These are dirty
experiments.  I think it's ok to leave them as ephemeral videos/blogs.

**Comment by mrocklin** [comment]
Video is up here: https://youtu.be/_x7oaSEJDjA
Tweet up here: https://twitter.com/dask_dev/status/1593593817772400646

Thank you everyone for participating!
