### ISSUE TITLE
Crick ownership

### ISSUE THREAD

**Issue by mrocklin** [dask/community#290]
The dask.distributed package has some optional dependency on crick.  Historically this was owned by @jcrist .  Jim has been busy with other things recently (small human + Ibis).  Maintenance of Crick was lagging a bit.  Jim has been kind enough to transfer the repo to https://github.com/dask/crick  and has given @jrbourbeau and I rights to PyPI.  

@fjetter this might affect some things in dask/distributed.  I'm not sure if you want to lean more into crick or less.  Let me know if you want James or I do to anything (like give you PyPI rights as well)

Nothing else to do here.  Closing this issue unless people want to reopen.

**Comment by mrocklin** [comment]
See also https://github.com/dask/crick/issues/25

**Comment by jakirkham** [comment]
Thanks for letting us know! :pray:

Also thanks Jim for your work getting Crick to where it is today 🙂
