### ISSUE TITLE
Moving dask-awkward to dask-contrib

### ISSUE THREAD

**Issue by douglasdavis** [dask/community#293]
The first official release of `dask-awkward` is planned for early December. Before that release we (@martindurant and myself) would like to have the repo (currently at https://github.com/ContinuumIO/dask-awkward) moved over to dask-contrib. The package is already available [from PyPI](https://pypi.org/project/dask-awkward/), but the first non-alpha release will come out in parallel with the first non-rc release of [awkward](https://pypi.org/project/awkward/#history) which should be the first week of Dec.

**Comment by douglasdavis** [comment]
@jrbourbeau I know you helped with getting dask-histogram moved over last year-- If I remember correctly if this gets the thumbs up I think we can just add you as an owner to the repo

**Comment by jrbourbeau** [comment]
+1 from me -- let's give some time for others to weigh in and then I'd be happy to help migrate over to `dask-contrib`

**Comment by jacobtomlinson** [comment]
+1

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson -- I'll plan to transfer `dask-awkward` over to `dask-contrib` later this afternoon (US time) if no further responses

**Comment by jrbourbeau** [comment]
Just transferred things over. @douglasdavis you should have admin permissions to handle anything that comes up as a result of the transfer, but feel free to ping me if there's anything else I can help with

**Comment by jacobtomlinson** [comment]
This seems like a nice milestone to reach so I've tweeted about it. https://twitter.com/dask_dev/status/1595355486727335937

Once we get to the point where the `This is alpha software without any guaranteed API stability.` warning in Dask Awkward can be removed we should put out a Dask blog post about it and share it more heavily.

**Comment by martindurant** [comment]
In the coming ~week, we (@douglasdavis ) will present at pydata global, and then a couple of weeks later an Anaconda webinar. In the meantime, awkward V2 will become official rather than release candidate, so everything will align.
