### ISSUE TITLE
Monthly Demo Day 2022-12-15

### ISSUE THREAD

**Issue by mrocklin** [dask/community#296]
## Announcement

We're cancelling this month's demo day due to the holidays

## Before

Our last [demo day](https://github.com/dask/community/issues/280) was a great success #286 !  https://www.youtube.com/watch?v=_x7oaSEJDjA&t=17s&ab_channel=Dask

We'd love to repeat this great success, now with more demos!

## When

Thursday, December 15th, at 10am US Central time (meeting invite below and also on the Dask calendar)

## Context

I'd like to solicit 5-10 minute demos that show off ongoing or lesser known work.  I hope to have 3-5 of these during the meeting.  Meetings will be recorded and advertised on social.  Hopefully this helps to educate folks on some of the great work people are up to.

If you're interested please respond to this issue with a brief (a couple sentences) description.  If you have colleagues who you think should be interested please let them know.

## Agenda

- Running many large xgboost.dask queries on many Dask clusters in parallel: @mrocklin 
- Parallelizing FTP downloads from a janky government server: @phobson 
- Configurable Dataframe backends : @rjzamora 
- .
- .

If there aren't enough spaces then I'll talk through GIL measurement

## Meeting Invite

Topic: Dask Demo Day
Time: 08:00 AM Pacific Time (US and Canada)
        Every month on the Third Thu, until May 21, 2026, 43 occurrence(s)

Please download and import the following iCalendar (.ics) files to your calendar system.
Monthly: [https://us06web.zoom.us/meeting/tZ0uf-qorT4tGtc673iGO0K1lLAN0XrtJ7DV/ics?icsToken=98tyKuGhrTMpGteQtxmERpx5A4qgb_TztiVajbdeyki2Cgd8MiinOs5jHOJHAsz6](https://www.google.com/url?q=https://us06web.zoom.us/meeting/tZ0uf-qorT4tGtc673iGO0K1lLAN0XrtJ7DV/ics?icsToken%3D98tyKuGhrTMpGteQtxmERpx5A4qgb_TztiVajbdeyki2Cgd8MiinOs5jHOJHAsz6&sa=D&source=calendar&usd=2&usg=AOvVaw0OMk88j5yqFaQyHRNmitIp)

Join Zoom Meeting
[https://us06web.zoom.us/j/89383035703?pwd=WkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09](https://www.google.com/url?q=https://us06web.zoom.us/j/89383035703?pwd%3DWkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09&sa=D&source=calendar&usd=2&usg=AOvVaw1GbPhE5xfqMKxyam1Ml-Qd)

Meeting ID: 893 8303 5703
Passcode: 130458
One tap mobile
+13462487799,,89383035703# US (Houston)
+16694449171,,89383035703# US

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 669 444 9171 US
        +1 669 900 6833 US (San Jose)
        +1 719 359 4580 US
        +1 253 205 0468 US
        +1 253 215 8782 US (Tacoma)
        +1 507 473 4847 US
        +1 564 217 2000 US
        +1 646 931 3860 US
        +1 689 278 1000 US
        +1 929 436 2866 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 305 224 1968 US
        +1 309 205 3325 US
        +1 312 626 6799 US (Chicago)
        +1 360 209 5623 US
        +1 386 347 5053 US
Meeting ID: 893 8303 5703
Find your local number: [https://us06web.zoom.us/u/kcspFo8Sig](https://www.google.com/url?q=https://us06web.zoom.us/u/kcspFo8Sig&sa=D&source=calendar&usd=2&usg=AOvVaw2YWRtQlAJPjagDlGxD8iQk)

**Comment by phobson** [comment]
Throwing my hat in the ring to demo what it looks like to convert an embarrassingly parallel and messy data transfer/parse text/dataframe/insights work flow to using dask.

**Comment by jrbourbeau** [comment]
Just checking in here, @mrocklin @phobson @rjzamora I see you three are currently on the agenda. Are things still good to go for this Thursday? Are there other folks who would also like to present?

**Comment by mrocklin** [comment]
Ah!  I had totally forgotten about this.  Thank you for the reminder James!

I'll try to drum up a couple of other speakers.  Anyone have any recommendations for people that we could pester?

**Comment by rjzamora** [comment]
I'll be happy to give a demo on backend creation dispatching, as long as it's okay that I keep the "presentation" bar low :)

**Comment by mrocklin** [comment]
Hooray for a low bar!

**Comment by phobson** [comment]
I too should be ready to present a janky workflow made faster with dask

**Comment by mrocklin** [comment]
Due to the holidays I'm inclined to delay this until next month.  Any objections?

**Comment by jrbourbeau** [comment]
No objection from me

**Comment by mrocklin** [comment]
I've removed the event from the calendar and updated the opening comment here to say that this is cancelled.  I'll also show up in the meeting for the first ten minutes and explain to any folks who show up (unless someone else wants to volunteer to do this)

**Comment by jrbourbeau** [comment]
Just seeing there's a demo day scheduled for tomorrow. Are folks still up for presenting? (sorry, should have looked ahead a bit more on my calendar)

**Comment by mrocklin** [comment]
I totally forgot about this.  I think that we should delete the event.
I'll go ahead with this if no one yells at me in the next hour or so

**Comment by mrocklin** [comment]
Removed for now

**Comment by phobson** [comment]
Are all future demo days cancelled?

**Comment by mrocklin** [comment]
Just this month's.  My apologies

**Comment by chrowe** [comment]
Next demo day is tomorrow! https://github.com/dask/community/issues/304
