### ISSUE TITLE
Brand Guide

### ISSUE THREAD

**Issue by jcrist** [dask/community#3]
Perhaps we should create a "brand guide", similar to what Jupyter has? https://github.com/jupyter/design/blob/master/brandguide/brand_guide.pdf. This would include usage policies for the logo and name, as well as standard colors for templates etc...

**Comment by jcrist** [comment]
This was prompted by my pet-peeve of people spelling Dask in all capital letters ("DASK"). Dask is not an acronym, when writing it should be spelled "Dask". Perhaps writing this down somewhere official will help, idk.

**Comment by jacobtomlinson** [comment]
We [have this in Pangeo](https://github.com/pangeo-data/branding) and it's super useful. Can also be a good place to share slide templates etc.

**Comment by mrocklin** [comment]
I threw together some content here as a sphinx site, but I'm not sure if that's better or worse than a PDF.  Also, the content could use a bunch of work.

https://github.com/dask/marketing

**Comment by datapythonista** [comment]
FYI pandas recently added this section to the website: https://dev.pandas.io/about/citing.html

There are discussions to standardize the navigation sections across NumFOCUS projects. So, this section or a similar one should be part of the standard.

**Comment by GenevieveBuckley** [comment]
So https://github.com/dask/marketing has been up for a while now and seems to be filling this need. I'll close this issue, unless anyone wants to add anything else to the discussion here.
