### ISSUE TITLE
Promoting related for-profit companies/technologies/orgs in Dask content

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#305]
I'd love to get a discussion going around how we as a community feel about promoting related for-profit companies/technologies/orgs in Dask content. 

When we talk about deploying Dask there are a bunch of OSS tools folks can use, but there are also folks like Coiled, Saturn, Quansight, etc who sell services around this.

When we talk about accelerating Dask there are projects in the ecosystem such as RAPIDS which can be used but that require you to buy/rent an NVIDIA GPU.

From a user perspective, these things are useful to know about because they potentially add value to them. From a purist-OSS perspective, it can feel funny to promote for-profit things. 

Recently some Coiled folks have been proposing PRs which link out to some of their products and content. https://github.com/dask/dask/pull/9933 https://github.com/dask/dask-tutorial/pull/275 https://github.com/dask/dask/pull/9912. Much of this makes sense to me as it talks about high-level topics such as what is required to run Dask within an organisation, Dask tutorials, etc. 

In the same vein, I'd love to start contributing more content on accelerating Dask workloads which would inevitably mention RAPIDS and link out to NVIDIA projects and content.

From a community perspective, I want to accommodate folks who are adding value to Dask users via their tools and services but also ensure that Dask always feels like a community project and doesn't slide down the slope to having a corporate open-core feeling. Projects like Elasticsearch spring to mind that have a for-profit vibe I don't want Dask to have.

One way I think we can achieve that is by keeping content on GitHub and using lists when we talk about external things. The PR that adds a "Tutorials from our community" section to the Dask tutorial does this nicely because it adds links to some Coiled and other company tutorials, but it clearly communicates that we are talking about external things and leaves it wide open for other folks to come in and contribute other links to the list.

I'd love for other folks to check out those PRs and generally give their thoughts on how we can find the right balance between pointing users to useful resources without being too promotional of for-profit stuff.

**Comment by jbednar** [comment]
Those are all good points. One thing to consider is whether the external companies that get promoted are directly contributing to pushing Dask's codebase forward. If they are, in some sense it's good for Dask to provide them exposure, since their success eventually feeds back to Dask's success.  But even in that case it's definitely important to make it clear when something is linking out to a commercial product or service.

**Comment by quasiben** [comment]
> From a community perspective, I want to accommodate folks who are adding value to Dask users via their tools and services but also ensure that Dask always feels like a community project and doesn't slide down the slope to having a corporate open-core feeling. Projects like Elasticsearch spring to mind that have a for-profit vibe I don't want Dask to have.

I like and agree with this statement. I think Coiled/Saturn definitely add value on top of Dask and it's useful to inform users/potential users that it does.

In general, I don't see much difference between the what the PRs linked above are proposing and the pre-existing pages on "Companies/Projects Powered by Dask" on the front page of dask.org.  FWIW I think it's ok to lean a bit more into corporate messaging/marketing and I'm not too concerned that we would be "too promotional" as we have a healthy dose of OSS culture within the Dask community.

**Comment by dharhas** [comment]
Nebari (formerly QHub) is somewhere in between. 

We've transitioned it to a community run open source model (currently most contributors are still Quansight). Essentially, it is an easy way to get Dask-Gateway, JupyterHub + several other integrations working in the cloud without needing to know k8s. 

That said we do have client who pay us to install and maintain it for them and we are planning to have some 'buckets of support hours' folks can purchase.

Overall I think as long as it is clear what is company backed and what is more community backed listing all the options is healthy.

**Comment by martindurant** [comment]
+1 for nebari. I use it sometimes via some climate colleagues. Since nebari has its own logo, that can be included as community.
Quansight might desire to be separately represented as commercial interest. We already mention(ed) Quansight as a company that can provide dask-related services.

**Comment by jacobtomlinson** [comment]
This has been open for a couple of weeks and the general consensus seems to be that we are happy to promote both for-profit companies as well as OSS communities backed by for-profit companies if they are providing value to the Dask community. The key thing is that we clearly label things as commercial in those situations.

I'm going to close this out and I welcome PRs from folks who want to add links and information throughout the Dask docs. Feel free to ping me for review. I'll likely start doing this for NVIDIA/RAPIDS things, and will ping non-NVIDIA Dask maintainers for review.
