### ISSUE TITLE
SciPy 2020 Tutorial

### ISSUE THREAD

**Issue by mrocklin** [dask/community#31]
I would love to see a Dask tutorial at SciPy 2020.  Do we know anyone who might want to deliver this tutorial?

**Comment by jrbourbeau** [comment]
This was brought up at the last monthly meeting. I plan to submit a Dask tutorial for SciPy 2020. Anyone who is interested in presenting (or knows of someone who would be interested) should feel free to comment here

**Comment by jrbourbeau** [comment]
cc @kkraus14 @mmccarty who mentioned there may be interest from people at their organziations

**Comment by mmccarty** [comment]
Definitely! I am planning on attending and can help.

**Comment by mrocklin** [comment]
I like the idea of James leading this.  It would be good to have at least one other person on the hook.  This includes both prepping materials, making sure that the infrastructure is working well, and then being in the tutorial itself to deliver and help.  It would be great if this person could come from CapOne or RAPIDS.  It is probably at least a week of half-time work.

**Comment by dharhas** [comment]
I'm available to help with this in whatever capacity is needed. I think we can probably round up some other Quansight folks who will be at SciPy to help in the room etc.

**Comment by jrbourbeau** [comment]
Great, thanks for volunteering @mmccarty @dharhas! I'll put together a draft tutorial proposal and post it here for review

**Comment by kkraus14** [comment]
Myself and others from the RAPIDS team will be there and can likely make ourselves available to be TAs / helpers during the tutorial, but we can't commit to helping with infrastructure or the proposal currently.

**Comment by jrbourbeau** [comment]
That'd be great, thanks @kkraus14! 

Here's a draft proposal for the tutorial: https://docs.google.com/document/d/1_5gOsn3WJ08Iws3LSMy-uoqpQC0EepOL0hl_JXjSs7k/edit?usp=sharing. It's largely based off the SciPy 2018 proposal. Any comment, suggestions, etc. are welcome

**Comment by jrbourbeau** [comment]
Just a heads up, I'm planning to submit the tutorial application later this afternoon

**Comment by dharhas** [comment]
@jrbourbeau I still think you should flip the order and do dask.dataframes first and then go to array, bag, and delayed. I think that is what I have seen as the most effective in my experience bringing new people up to speed who want to use dask as a tool.

**Comment by jakirkham** [comment]
This seems really nicely laid out. Thanks for working on this James! 😀

**Comment by jrbourbeau** [comment]
I heard back from the conference organizers yesterday and our tutorial has been accepted 🎉

**Comment by dharhas** [comment]
SciPy 2020 is going virtual. They have the following request for our tutorial:

> The details of how these tutorials will be presented have yet to be completely worked out, but we are roughly planning on asking presenters to pre-record a number of short (20ish) minute video segments where materials and demonstrations are presented. These pre-recorded segments will be interspersed with 15 or 20 minute interactive sessions where students try doing exercises and the instructors are available for questions on those exercises.

We need to respond on whether we are interested in conducting the tutorial this way. I'm open to doing this. 

thoughts @jrbourbeau @mmccarty ?

**Comment by jrbourbeau** [comment]
I'm also open to doing this. We could include the recorded bits in the `dask-tutorial` repo

**Comment by mmccarty** [comment]
I'm game.

**Comment by dharhas** [comment]
Great. I'll respond to the email saying we are in.

**Comment by mrocklin** [comment]
Hrm, we have a similar opportunity for PyCon.  @TomAugspurger and I decided
to pass.  If you all are interested in doing this twice (presumably this is
easier the second time) we could ask them if they're comfortable changing
around the speakers.

**Comment by dharhas** [comment]
What is the PyCon timeline. That pretty soonish right? I'm open to considering it but the shorter timeline means I need to check calendar.

**Comment by mrocklin** [comment]
Upload by April 24th

**Comment by jrbourbeau** [comment]
I personally think April 24th is a little too soon. I don't think I'll have much time to go through / update the tutorial materials over the next two weeks

**Comment by mrocklin** [comment]
Sounds good.  We'll just continue not responding positively to them then

**Comment by mmccarty** [comment]
Any updates on this? Are we committed? Or did we pass?

**Comment by dharhas** [comment]
We passed on PyCon tutorial, but we are doing the SciPy tutorial.

**Comment by mmccarty** [comment]
@dharhas @jrbourbeau I've created a private slack channel on the SciPy 2020 workspace to coordinate. Ping me once you're in and I'll add you.

**Comment by martindurant** [comment]
Happy to help, if you need more hands

**Comment by jrbourbeau** [comment]
Closing, thanks @dharhas @mmccarty for presenting at SciPy this year!
