### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#33]
Dask master has a few fixes with compatibility for pandas 1.0. I'd like to make a Dask release shortly before the pandas release, which will likely happen tomorrow or Wednesday.

Are there any objections to me releasing Dask and Distributed at around the same time as pandas?

**Comment by jakirkham** [comment]
+1

**Comment by jrbourbeau** [comment]
+1 from me too. We'll want to make sure we don't merge the [distributed Python 3.8 PR](https://github.com/dask/distributed/pull/3249) (which isn't complete, but is close) prior to this release

**Comment by mrocklin** [comment]
+1

**Comment by jrbourbeau** [comment]
Just for reference, I missed up the version number on the last `dask` + `distributed` release. We had been incrementing the minor version number for our normal ~bi-weekly release, but last time I accidentally incremented the bugfix version instead (i.e. went from `2.9.1` -> `2.9.2`). This next release should be `2.10.0`.

**Comment by jrbourbeau** [comment]
Closing as version `2.10.0` of dask and distributed are on PyPI and the the conda-forge feedstocks have been updated. Thanks @TomAugspurger!

**Comment by mrocklin** [comment]
Does anyone want to push out a tweet, and maybe mention the Pandas 1.0
release as motivation?

**Comment by TomAugspurger** [comment]
Ah yeah, I meant to do that. 1 sec.

**Comment by jakirkham** [comment]
Thanks for managing this release Tom! 😄
