### ISSUE TITLE
Monthly meeting

### ISSUE THREAD

**Issue by mrocklin** [dask/community#34]
As a reminder, the monthly meeting will be held this Thursday.  

- [Agenda](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit)
-  [Video conference](https://zoom.us/j/802251830)

**Comment by jrbourbeau** [comment]
Thanks for the reminder @mrocklin, see you all next month!
