### ISSUE TITLE
Move dask-databricks to dask-contrib

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#353]
I'd like to move [jacobtomlinson/dask-databricks](https://github.com/jacobtomlinson/dask-databricks) over to @dask-contrib as it now contains a feature-complete MVP and is published to PyPI and conda-forge. 

The project is targeted at Databricks users who launch multi-node Spark clusters, giving them the ability to conveniently launch a Dask cluster alongside Spark running on the same hardware, making it very easy to try out Dask in their existing workflows.

**Comment by quasiben** [comment]
+1 I think this would great to have -- largely it seems like a lot of work is done it's just a namespace issue

**Comment by jacobtomlinson** [comment]
Thanks! If there are no further comments here I intend to move this over at the end of the week.

**Comment by jacobtomlinson** [comment]
Transfer is complete https://github.com/dask-contrib/dask-databricks 🎉
