### ISSUE TITLE
Dask Demo Day 2024-03-21

### ISSUE THREAD

**Issue by scharlottej13** [dask/community#368]
When
---
Thursday, March 21, at 10am US CT.

Meeting invite below and also on the Dask calendar:

- [Google Calendar](https://calendar.google.com/calendar/u/0?cid=NGwwdnRzMGMxY2dkYnE1amhjb2dqNTVzZnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)
- [iCal](https://calendar.google.com/calendar/ical/4l0vts0c1cgdbq5jhcogj55sfs%40group.calendar.google.com/public/basic.ics)

Agenda
---

- @fjetter recent Dask DataFrame improvements
- @mrocklin on large scale population of vector databases for RAG
- @jrbourbeau easy GPU debugging
- ...

Past demo day agendas listed in https://github.com/dask/community/issues/307

Meeting Invite
---
Join Zoom Meeting
[https://us06web.zoom.us/j/89383035703?pwd=WkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09](https://www.google.com/url?q=https://us06web.zoom.us/j/89383035703?pwd%3DWkRJSzNnRTh4T2R1ZjJuVVdJWlMxQT09&sa=D&source=calendar&ust=1703567093706137&usg=AOvVaw1MyxxrsENRTk07R18qM1TF)

**Comment by scharlottej13** [comment]
@rjzamora [last month](https://github.com/dask/community/issues/364#issuecomment-1941848842) you mentioned you might have some ML work to show? Are you up for presenting this month?

**Comment by jrbourbeau** [comment]
I pinged @rjzamora offline and he mentioned this week doesn't work well (which is totally fine)

**Comment by jacobtomlinson** [comment]
@scharlottej13 is there a recording for this?

**Comment by scharlottej13** [comment]
Thanks for the reminder @jacobtomlinson! Recording is up https://youtu.be/HTKzEDa2GA8
