### ISSUE TITLE
End of Python3.9 support

### ISSUE THREAD

**Issue by fjetter** [dask/community#373]
It's the time of the year again where [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) "allows" us to drop a python version. 

Numpy already dropped support https://github.com/numpy/numpy/issues/26242 / https://github.com/numpy/numpy/pull/26222
Pandas is still supporting it. The only issue I could find that relates is https://github.com/pandas-dev/pandas/issues/55528

Are there any objections from the community to drop python 3.9 support?

**Comment by jacobtomlinson** [comment]
No objection from me!

**Comment by jakirkham** [comment]
> Pandas is still supporting it. The only issue I could find that relates is [pandas-dev/pandas#55528](https://github.com/pandas-dev/pandas/issues/55528)

Pandas is also dropping Python 3.9 as of PR: https://github.com/pandas-dev/pandas/pull/58238

It is yet to be included in a release

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/11245, https://github.com/dask/distributed/pull/8793, https://github.com/dask/dask-expr/pull/1109
