### ISSUE TITLE
New virtual meeting for Dask Maintainers Sync

### ISSUE THREAD

**Issue by hendrikmakait** [dask/community#377]
We've recently hit a few issues with whereby.com which caused the maintainers sync to migrate to Google Meet. The new meeting can be found at https://meet.google.com/mam-nagt-msx. We still need to update the Calendar event. @mrocklin, I suspect you have the necessary permissions, could you take care of this?

**Comment by mrocklin** [comment]
I've added you to the calendar, so that hopefully you have sufficient
permissions to make this change yourself (let me know if not though and I
can do it)

**Comment by hendrikmakait** [comment]
Done, thanks!
