### ISSUE TITLE
Release 2.3.0

### ISSUE THREAD

**Issue by mrocklin** [dask/community#4]
We should push out a release of dask/dask and maybe dask/distributed . 

I don't think that there are breaking changes in dask/distributed for downstream deployment projects (jobqueue/kubernetes), but we should check.

**Comment by jrbourbeau** [comment]
Both dask-jobqueue (ref https://github.com/dask/dask-jobqueue/pull/313) and dask-kubernetes (https://github.com/dask/dask-kubernetes/pull/171) are compatible with the current `master` branches of dask and distributed. Planning to do a 2.3.0 release of dask/dask and dask/distributed this afternoon

**Comment by mrocklin** [comment]
If possible could I ask that we get
https://github.com/dask/distributed/pull/2948 in beforehand?  I think that
we're fairly close, and this would resolve a bug in RAPIDS work.

**Comment by jrbourbeau** [comment]
Yeah, not a problem

**Comment by mrocklin** [comment]
@jrbourbeau I'm good to go.  I wouldn't mind also getting in https://github.com/dask/distributed/pull/2961 , but would be happy to skip that if you'd like to get moving.  I think that we could probably also safely merge that without CI.

**Comment by jrbourbeau** [comment]
Waiting for the CI is fine by me. I'll keep a look out and merge https://github.com/dask/distributed/pull/2961 on green

**Comment by mrocklin** [comment]
Merged.  Fire away.

**Comment by jrbourbeau** [comment]
Closing as the 2.3.0 release for dask and distributed is up on GitHub, PyPI, and conda-forge
