### ISSUE TITLE
April 2020 Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#41]
As a reminder, the monthly meeting will be held this Thursday.  

- [Agenda](https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit)
-  [Video conference](https://zoom.us/j/802251830)
- Calendar: https://docs.dask.org/en/latest/support.html#discussion

**Comment by jakirkham** [comment]
Is the Google calendar event pinned to a timezone that follows daylight savings time or does it use UTC? Asking as when I checked the meeting time yesterday based on the calendar event, it showed it being 9a PDT, but it appears that it should have been 8a PDT.

**Comment by TomAugspurger** [comment]
I recall having an issue when importing a shared google calendar into my own local calendar. Now I reference https://docs.dask.org/en/latest/support.html#discussion, which is pinned to 10:00 US Central time.

**Comment by jakirkham** [comment]
Thanks Tom! 😄
