### ISSUE TITLE
Creating teams for dask-jobqueue by scheduler ? 

### ISSUE THREAD

**Issue by lesteve** [dask/community#42]
For some time I have been thinking about creating teams for Dask-Jobqueue by
jobqueue schedulers (SLURM, SGE, PBS, etc ...) so that relevant people could be pinged like `@dask/lsf-champions` (or `@dask/dask-jobqueue-lsf-users` or something else). The idea would be that some scheduler-specific issues are best handled by people who have access to a simlar cluster.

I believe that:
- teams are at the Dask org level not the dask-jobqueue repo
- I have the rights to create such teams in the Dask org

Just wanted to get some feed-back in case you see a problem with this ?

I have not settled down on a name yet, suggestions more than welcome!

Of course if you have access to a HPC cluster and want to volunteer to be included in one or more teams like this, let me know!

**Comment by jakirkham** [comment]
Is it possible to do subteams? Like `@dask/jobqueue/lsf`

**Comment by lesteve** [comment]
Good questions, I don't really know but I'll try to google it ...

**Comment by mrocklin** [comment]
We don't currently have much experience using teams, but I think that it
would be good to experiment and learn.  I agree with @lesteve that this use
case in Dask Jobqueue sounds ideal.

**Comment by mrocklin** [comment]
Also +1 on subteams if possible

**Comment by gforsyth** [comment]
nested teams are definitely a thing, not sure how the `@` shortcuts work with them, though, or if each level needs unique names.

**Comment by lesteve** [comment]
I did not know about [nested teams](https://github.blog/2017-06-13-nested-teams-add-depth-to-your-team-structure/) nice.

For simplicity I am going to use names like `@dask/dask-jobqueue/slurm` unless someone has a strong objection:
- it feels easier if dask/dask-jobqueue like the repo name
- I feel the name is already long enough that I don't need to add more to the end, like `slurm-champions` or `slurm-users`

If noone objects I'll go ahead and create a few teams, start to put some people in them and let you know how I get on.

**Comment by jakirkham** [comment]
Sounds good 🙂

**Comment by lesteve** [comment]
I created the teams and now I am trying to get some volunteers in https://github.com/dask/dask-jobqueue/issues/410. Thanks a lot for your feed-back!

One thing with subteams that could be useful that I realised only recently is to have a @dask/dask-jobqueue parent team with some permissions for closing, labeling issues, etc ...

**Comment by jakirkham** [comment]
Yep, we use this at conda-forge with our language specific help teams 🙂

**Comment by lesteve** [comment]
Of course, I am discovering caveats when trying to implement this ... 
- to add a person to the `dask/dask-jobqueue/slurm` team it needs to be a member of the Dask organization
- Only organization owners can add users to an organisation according to https://help.github.com/en/enterprise/2.16/user/github/setting-up-and-managing-organizations-and-teams/adding-people-to-your-organization 

What is the right way to proceed ? Would it be fine to make me an owner of the Dask organization ? An alternative would be for me to send a list of people once it stabilizes to add to the Dask organization.

Also it is going a bit cumbersome to add all the people (~20) by hand if you know nifty tools to do this, I am interested!

**Comment by mrocklin** [comment]
Ownership is possible, but would take time to get buy in from other owners
(there is a formal governance process around this).

Until then I'm more than happy to add people to a list if you want to send
me a list.  I'm happy to do this manually (my guess is that this is more
time efficient short-term than finding an automated tool).

**Comment by lesteve** [comment]
Makes complete sense, so I would say:
- short term, I'll send you a list once it stabilizes. Maybe here are some people that I noticed should probably be already in the Dask org: `@andersy005`, `@willirath` independently from my ongoing effort with Dask-Jobqueue teams 
- longer term, why not about Dask ownership thing, I'll read the governance documents in more detail to get a better feeling what it entails exactly

Also agree about the low-tech approach, we all know the xkcd I am thinking of.

**Comment by lesteve** [comment]
So some people have been added to the Dask organization and I have started creating teams, so I am going to close this one. Thanks everyone for your inputs!
