### ISSUE TITLE
Stale issue closing sprint

### ISSUE THREAD

**Issue by jsignell** [dask/community#47]
In the developer meeting on Tuesday, we (me, @quasiben, @gforsyth, @dankerrigan) agreed to meet up and close out stale issues. I proposed on gitter that we do that on Thursday (4/30) morning. Does that work for people?

**Comment by quasiben** [comment]
That works for me.  I am free from 9 to 12 EST and then again from 1pm to 4PM

**Comment by gforsyth** [comment]
I'm free from 9 to 10:30 EST, then from 3pm EST on.

**Comment by jsignell** [comment]
Ok! Should we just start at 9 tomorrow and see how things go?

**Comment by gforsyth** [comment]
Sounds good to me!

**Comment by quasiben** [comment]
We met and it was great!  Closed and responded to a lot of issues on the dask tracker.  We should do it again.  Thank @jsignell for organizing and @gforsyth @dankerrigan for participating.  I don't have access to close but I think we can close this

**Comment by jrbourbeau** [comment]
Thanks all for working on this! It was great to see your progress through the issue tracker : )
