### ISSUE TITLE
GitHub @dask/maintenance team

### ISSUE THREAD

**Issue by jsignell** [dask/community#53]
I made a new team called @dask/czars for the people currently on maintenance duty. I was hoping that would make it easy to keep track of who is on that team at any given time and people can mention the team to draw something to the maintenance group's attention. As mentioned in https://github.com/dask/community/issues/49#issuecomment-628677496 this team should be updated routinely as people cycle on and off of the maintenance team. 

Hote: I couldn't add @dankerrigan because he's not a member of the org yet. I recommend that he be added.

**Comment by mrocklin** [comment]
> Note: I couldn't add @dankerrigan because he's not a member of the org yet. I recommend that he be added.

Invite sent

> I made a new team called @dask/czars for the people currently on maintenance duty.

Thanks @jsignell !  For the benefit of new folks to the project I recommend that we rename this to `@dask/maintenance` .  I think that this will be more clear to newcomers who are submitting an issue for the first time.  Thoughts?

**Comment by jsignell** [comment]
> I recommend that we rename this to `@dask/maintenance`.

The only issue is that I have trouble reliably spelling maintenance. But I guess czar has multiple spellings as well and autocomplete exists, so fine by me :upside_down_face:

**Comment by mrocklin** [comment]
Auto-complete to the rescue!

**Comment by TomAugspurger** [comment]
We're doing this now, though we aren't perfect about cycling people on and off.
