### ISSUE TITLE
arrange IO meeting

### ISSUE THREAD

**Issue by martindurant** [dask/community#55]
@dask/io , when would people be free to get together to discuss parquet, filesystems, etc?

**Comment by TomAugspurger** [comment]
I'm free tomorrow other than 11:00 - 1:30 Central. Or Thursday after 1:00,
or most of Friday.

Tom

**Comment by martindurant** [comment]
I prefer thursday or friday

**Comment by rjzamora** [comment]
I'm most open Thursday morning this week (Central Time)

**Comment by TomAugspurger** [comment]
I can do Thursday morning other than 10:30 - 11:00 central.

**Comment by TomAugspurger** [comment]
We had our original IO meeting. We don't have a standing meeting, but can certainly set one up if needed.
