### ISSUE TITLE
Dask User Survey 2020

### ISSUE THREAD

**Issue by mrocklin** [dask/community#56]
We ran the 2019 Dask user survey about one year ago. ([summary here](https://blog.dask.org/2019/08/05/user-survey))

We should think about running this again.  This raises some questions:

### How should we change the questions?

There is some value to remaining consistent with last year so that we can observe change.

There is also some value in learning from the responses of last year.  Some of the responses were super valuable (apparently SSH is the most common deployment strategy) and some of the responses we never really analyzed again (I'm thinking of the larger tables).  

What are some changes that we should make from last years' template?

A copy of the 2019 form [is here](https://forms.gle/1mPPYBFpnNZ4Cj3PA) (the actual form is now closed).

### Advertise

Last year we mostly advertised this on Twitter, and also at various conferences.  What else can we do?

I plan to do a fair bit of writing starting about a week or two from now, and hopefully I can funnel users towards the survey (assuming we get something up by then).  Are there other opportunities here?

cc @TomAugspurger in particular, who helped to analyze the data from last year.

**Comment by TomAugspurger** [comment]
I'd keep most of the questions the same to aid with comparing things year over year.

* I'm curious if we'd like to change any of the items in "What common feature requests do you care about most?". I'm not sure I would change any
* We can drop the Python 2 or 3 question probably.
* Add Dask-Cloudprovider and Dask-Gateway to "If you use a cluster, how do you launch Dask?"
* Add a disclaimer that we'll publish the responses to the non-sensitive questions (won't publish the responses to the last page)

**Comment by jacobtomlinson** [comment]
Agreed that keeping things the same really helps with comparisons over time.
 
Could we add some dashboard questions? Something like:

- How do you view the dashboard, web page or labextension?
- Which plots do you find most useful?
- What info do you wish you could see on the dashboard?

And maybe some around the docker and helm chart.

- Do you use the Dask docker image?

Could we split the kubernetes option in the deployments section into `dask-kubernetes` and `helm chart`?

**Comment by jsignell** [comment]
I know I'm sneaking in at the end, but it'd be interesting to know what fields are using dask - especially if they've indicated that they want more examples in their field. We'd want to provide a list of industries though to make this useful (I'm happy to find this list if people like the question).

It'd also be interesting to get the split between people in academia and industry. Maybe something like

You work at a:
 - university
 - government research institution
 - company
 - <fill in the blank>

**Comment by mrocklin** [comment]
OK, there is a draft up here: dask.org/survey

Some changes:
1.  I dropped the Python 2/3 question
2.  I added a section after "what technologies do you use to deploy (HPC, Kubernetes, Yarn)" that asks what Dask packages you use (dask-kubernetes, dask-help, dask-docker, etc.)  This feels somewhat redundant, but captures a few of the questions above
3.  I added a question on how they use the dashboard, but I didn't ask about which plots people find most useful, mostly because I don't know of a way to name them that users will immediately get (keeping questions easy is a big part of survey design I think)
4.  I added a disclaimer in the front-matter that we're going to be publishing non-sensitive answers
5.  I asked for a name and company name in the final section.  This isn't quite the same as asking people to segment between university/industry/government but gets us some of the same information.

**Comment by TomAugspurger** [comment]
This is mostly done, just need to publish the blog post https://github.com/dask/dask-blog/pull/74.
