### ISSUE TITLE
Add pangeo multi-cloud demo to Dask Youtube account 

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#63]
I have an 11ish minute video demonstrating a Pangeo workflow to analyze datasets with two Dask clusters: one in AWS and one in GCP.

Any objections if I publish that on the Dask youtube account? I'm uploading it now and can share the URL if anyone wants to preview it first.

**Comment by mrocklin** [comment]
+1 from me.

FWIW I tend to just push content around open work without asking
permission.  I think that we should probably continue with this policy
until it becomes problematic.

**Comment by TomAugspurger** [comment]
Great thanks. It's public at https://www.youtube.com/watch?v=IeKjLiUqpT4 for those who are interested.
