### ISSUE TITLE
Release dask 2.18.1

### ISSUE THREAD

**Issue by jsignell** [dask/community#65]
We are currently breaking xarray tests with https://github.com/dask/dask/issues/6296 so it'd be nice to push a release of dask/dask

**Comment by mrocklin** [comment]
A potentially messy change went into distributed this morning:
https://github.com/dask/distributed/pull/3853

It'd be good *not *to release that package for a week or two to see if the
folks working on master report anything.

The Xarray failure is also only when running Python in optimized mode,
which is very rare.  I would be in favor of doing a point release for only
dask/dask, or waiting a few more days (if the Xarray people don't mind).

**Comment by jrbourbeau** [comment]
> I would be in favor of doing a point release for only dask/dask

+1. I'm happy to do a release of _just_ dask/dask this afternoon if nobody minds

**Comment by jakirkham** [comment]
SGTM

**Comment by jrbourbeau** [comment]
Closing as 2.18.1 is out. Thanks all!
