### ISSUE TITLE
July 2020 Monthly Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#70]
The monthly Dask meeting is this Thursday, July 3rd.

Video call: https://zoom.us/j/802251830
Agenda: https://docs.google.com/document/d/1UqNAP87a56ERH_xkQsS5Q_0PKYybd5Lj2WANy_hRzI0/edit.

Check the calendar at https://docs.dask.org/en/latest/support.html# for the time of the event (15:00 UTC).

Please add items you'd like to discuss to the agenda.

**Comment by jrbourbeau** [comment]
Thanks, as always, for the reminder @TomAugspurger!
