### ISSUE TITLE
Dask CZI Life Sciences Fellow job posting

### ISSUE THREAD

**Issue by mrocklin** [dask/community#72]
I've drafted up a job posting here.  I'm going to send it along to NumFOCUS for posting in 24 hours if there aren't any major issues with it.  If people have a chance to comment before then that would be welcome.

https://docs.google.com/document/d/108cIYUfi2TjbMOtBx1SjvrL7siqnEH3J9V0QJKZF47I/edit?usp=sharing

**Comment by jakirkham** [comment]
Thanks for writing that up, Matt! Seems good to me 😄

**Comment by mrocklin** [comment]
Thanks for reading it over!

**Comment by jcrist** [comment]
Perhaps add a sentence or two about how/who they'll be working with (we may not have this figured out yet ourselves?). If I was applying for a job I'd want to know more than just what I would be doing, but how my day-to-day/week-to-week work life would be.

**Comment by quasiben** [comment]
Looks good to me as well.  To address @jcrist's concern we could say something like:

> This individual will (you) spend time with dask maintainers, downstream users (potentially napari/scanpy folks), evangelize to new users

**Comment by GenevieveBuckley** [comment]
Probably could close this issue now :)

**Comment by jrbourbeau** [comment]
Woo 🎉
