### ISSUE TITLE
Dask Blogs

### ISSUE THREAD

**Issue by quasiben** [dask/community#73]
We have 5 maybe 6 blogs in the [pipeline](https://github.com/dask/dask-blog/pulls) and most seem to be approaching a done state.  We could do a few things here:

1) Release them as they are ready (blog dump)
2) With a large back log we could release regularly on a given day per week
3) something I haven't though of

Personally I am in favor of spreading the content out over the coming weeks

**Comment by TomAugspurger** [comment]
+1 for spreading them out a bit.

**Comment by jsignell** [comment]
Maybe we should do them on Thrusdays in order of urgency and doneness:

Proposal:
 - 2020-07-16: https://github.com/dask/dask-blog/pull/68
 - 2020-07-23: https://github.com/dask/dask-blog/pull/64
 - 2020-07-30: https://github.com/dask/dask-blog/pull/63

By then some of the other ones will probably be ready and can be scheduled for release.

**Comment by jsignell** [comment]
Ok! @jacobtomlinson merged the first one :)

**Comment by jsignell** [comment]
It seems like we are now good on this and we have the ability to merge future posts with the dates set thanks to @jacobtomlinson! Should I close this?

**Comment by quasiben** [comment]
+1 on closing
