### ISSUE TITLE
Tweet at each release?

### ISSUE THREAD

**Issue by mrocklin** [dask/community#81]
If the folks doing the releases (@jrbourbeau @jakirkham ) are up for it I propose that we issue a tweet from `@dask_dev` that says something like the following:

```
Dask 2.XX.X has just been released!

Notable features include 
1. ...
2. ...
3. ...

Full release notes are available here: ...
```

This would require a bit of mental work because we'll need to pick out three notable features but hopefully having just gone through the changelog this will be easy-ish at this time.  

Thoughts?  "Na, too much work, let's keep releases lightweight" is a totally valid retort I think.

**Comment by jakirkham** [comment]
I'm ok with someone doing this, but am not a Twitter user personally 🙂

**Comment by jrbourbeau** [comment]
Yeah, I'm on board with trying this out! Seems like a reasonable idea, but I'll reserve the right to say "Na, too much work" later on if that ends up being the case. 

We're pushing out 2.22.0 shortly, so I'll give it a try then

**Comment by jakirkham** [comment]
Might be possible to do this with [a GitHub Action]( https://github.com/marketplace/actions/twitter-action ).

**Comment by jrbourbeau** [comment]
https://twitter.com/dask_dev/status/1289342198534660096

**Comment by jrbourbeau** [comment]
Thanks for the suggestion @mrocklin

**Comment by jacobtomlinson** [comment]
As always I would be a fan of automating this as @jakirkham suggests. We could have a label for "Notable" or similar which we could add when merging a notable PR. Then the action would grab the PR titles with that label to construct the tweet.

**Comment by mrocklin** [comment]
I would encourage us to do this manually for a while first before we
automate it in order to get a hang on what we want.

**Comment by jcrist** [comment]
Since tweets have a limited length, and PR titles may not always be curated for "tweetability", I think automating this in a satisfying way would be hard.
