### ISSUE TITLE
Maintainer pairing time

### ISSUE THREAD

**Issue by jsignell** [dask/community#82]
I keep mentioning this and then forgetting to make an issue. The idea is that it is sometimes nice to triage bugs and look over PRs synchronously. Friday morning is often a good time for me to do this. Perhaps at 10am eastern?

@jrbourbeau

**Comment by jrbourbeau** [comment]
That sounds great to me, thanks for proposing we try this! 10 AM ET works for me. Let's give it a try this Friday on whereby

**Comment by jsignell** [comment]
Great! See you there :)

**Comment by jsignell** [comment]
I'm hanging out in the room now if anybody wants to chat :)

**Comment by jsignell** [comment]
That was fun :) nice to chat with Martin and Jacob. I am planning on keeping doing this if anyone else wants to drop by next week.

**Comment by jacobtomlinson** [comment]
I also enjoyed this. It was good to chat about a few Dask related issues. It was good to also just chat more generally. 

I strongly encourage that the Dask maintainer team behaves as we do with our regular employed teams and make time for a bit of social chat and tangential conversations. Thanks for driving this @jsignell.

**Comment by mrocklin** [comment]
Pangeo runs bi-weekly coffee breaks.  Maybe we should do something similar?

**Comment by jsignell** [comment]
I'll be in the room for the next half hour if anyone wants to drop by :)

**Comment by jsignell** [comment]
Doing this again now :)

**Comment by jsignell** [comment]
I have fallen off this a bit, but was wondering if it might make sense to move it to an evening. I'm going to try doing it on Thursdays at 5:30pm eastern. Ping @GenevieveBuckley in case you are interested in joining :)

**Comment by martindurant** [comment]
Perhaps, as a global collaboration, we should start quoting times in UT :)
I'm generally parenting in the evenings.

**Comment by jsignell** [comment]
Yeah I tried for a while to make a public google cal link, but I failed. I added a link to my message that maybe helps?

**Comment by GenevieveBuckley** [comment]
I'm very interested in joining. Ditto for coffeebreaks, etc. (although my timezone means a USA late afternoon break or after work happy hour might match well with a mid morning coffee here)

It seems I'm an hour too late today, I'll put this in my calendar for next week @jsignell

**Comment by GenevieveBuckley** [comment]
@jsignell can you send me a link to the room you'll be using? (Feel free to send it to me in the dask slack if you don't want to make it publicly available)

**Comment by jsignell** [comment]
I'll be in there whereby!

**Comment by GenevieveBuckley** [comment]
> I have fallen off this a bit, but was wondering if it might make sense to move it to an evening. I'm going to try doing it on Thursdays at [5:30pm eastern](https://everytimezone.com/s/c7ad91ec). Ping @GenevieveBuckley in case you are interested in joining :)

Just so other people know, the 'every time zone' link here is showing me incorrect information (somehow it's 24 hours off for me). The correct time is: Thursdays 5:30pm US Eastern time (UTC-5)

**Comment by jsignell** [comment]
Oh :facepalm: that was definitely me just using it wrong. Here's a better link hopefully: https://everytimezone.com/s/359e9f27

**Comment by GenevieveBuckley** [comment]
Julia says it would be better for her if we shifted the weekly time half an hour earlier. New time is https://everytimezone.com/s/57686c80

@jsignell @jrbourbeau

**Comment by jacobtomlinson** [comment]
The new time is past my bedtime (timezones are hard 😄). So I just want to raise that I'm always up for ad-hoc pairing too. Probably easiest or organize via the Dask slack.

**Comment by jsignell** [comment]
Another option is to alternate morning and evening (from my perspective) by the week a-la-pangeo. I'm down to try to figure out how to set up a recurring calendar thing if that appeals.

**Comment by GenevieveBuckley** [comment]
I'm +1 on alternating

**Comment by jacobtomlinson** [comment]
Sounds good!

**Comment by jsignell** [comment]
Ok! So on alternating weeks. It'll be at the old time Friday: 10am eastern. Let's do a morning one this week!

**Comment by GenevieveBuckley** [comment]
After Easter, the time difference changes so that it's too early in the morning for me. (There's a tiny bit of overlap between me & the west coast of the US, but not for the east coast.) So when that happens you can go back to the same time every week, or whatever else you like.

**Comment by jsignell** [comment]
I'll be in the room for the next half hour in case anyone wants to drop by :)

**Comment by GenevieveBuckley** [comment]
Does anyone on the west coast of the USA want to join me at a different time (say 4pm Pacific Daylight Time)?  @jakirkham? Is there anyone else in that timezone?

Daylight savings changes on April 4th for me, which pushes the current maintainer pairing time into when I'm asleep. This has been very useful for me, so I don't want to stop completely.

**Comment by GenevieveBuckley** [comment]
@ian-r-rose it seems you're also on the US west coast. Would you be up for a half hour coffee & dask chat on a semi-regular basis? In practice these are fairly relaxed.

**Comment by GenevieveBuckley** [comment]
I'm around now, if anyone wants to chat

**Comment by jsignell** [comment]
I think this is superseded by https://github.com/dask/community/issues/142 now, so I'm going to close this one :)
