### ISSUE TITLE
Add coordinated disclosure plan

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#88]
I'm setting up tidelift for Dask, and one of the work items is a [coordinate disclosure plan](https://vuls.cert.org/confluence/display/Wiki/Coordinated+Vulnerability+Disclosure+Guidance). This is a process for users to report vulnerabilities and us to acknowledge and potentially address them.

If we want, we can use Tidelift's process. Users go through the steps at https://tidelift.com/docs/security and we get an email from Tidelift. Otherwise, we can define our own process. Regardless of whether we use tidelift's or our own, we'll add a `SECURITY.md` file to https://github.com/dask/.github, which will be inherited by all repositories in the dask org.

Out of laziness, I'm fine with just using tidelift's process.

**Comment by jrbourbeau** [comment]
No strong opinion from me. Using Tidelift's process or something like "e-mail security@dask.org" seems fine to me

**Comment by quasiben** [comment]
Either one seems fine.  Though who gets the email ?

**Comment by TomAugspurger** [comment]
If we go through tidelift, we provide an email address that they contact. I
think we'll want to have a dask-security google group that the email goes
to to avoid a single point of failure.

**Comment by jakirkham** [comment]
SGTM

**Comment by TomAugspurger** [comment]
I've created `dask-security@googlegroups.com`. Anyone can email there, but only members can view the emails / posts. Who would like to join? I'll nominate

- @jcrist (since Dask Gateway has some security-related code)
- @jacobtomlinson (dask-kubernetes, dask-cloudprovider)

Does James, Ben, John, or anyone else want to join in the fun?

**Comment by jacobtomlinson** [comment]
Sounds good

**Comment by mrocklin** [comment]
I'd be happy to join the group

**Comment by mrocklin** [comment]
I recommend that we ask NumFOCUS for a GSuite account (they've offered this
in the past).  That way we can have things like security@dask.org, which I
think seems nicer.  I'll plan to do this tomorrow if there are no
objections.

**Comment by TomAugspurger** [comment]
Yep, that sounds good.

**Comment by quasiben** [comment]
Happy to be included as well

**Comment by jrbourbeau** [comment]
Same here, feel free to include me. Thanks for handling all this Tom
