### ISSUE TITLE
Dask maintainers on PyPI

### ISSUE THREAD

**Issue by TomAugspurger** [dask/community#89]
Could all the current maintainers on PyPI verify that they have enabled two 2-factor authentication on PyPI? Instructions are at https://pypi.org/manage/account/.

- [x] @jakirkham 
- [x] @jcrist 
- [x] @jrbourbeau 
- [x] @mrocklin 
- [ ] @sinhrks 
- [ ] @shoyer 
- [x] @TomAugspurger 

Additionally, would @sinhrks or @shoyer be offended if we removed them from the list of maintainers, since they aren't actively releasing Dask these days? :)

**Comment by jakirkham** [comment]
Not exactly related, but I don't have access to `distributed` on PyPI. Would it be possible to get access?

**Comment by mrocklin** [comment]
I didn't have this set up before but should have.  It was nice to be nudged here.

**Comment by shoyer** [comment]
I don't need access to release dask on pypi :)

**Comment by TomAugspurger** [comment]
OK I've removed @shoyer and @sinhrks as owners on PyPI. Thanks all :)
