### ISSUE TITLE
Upcoming release schedule around high level graphs

### ISSUE THREAD

**Issue by mrocklin** [dask/community#99]
We've been doing some work on high level graphs (HLG) to improve scheduler efficiency.  This includes major changes relatively low down in the collections' handling of graphs, optimization, and the scheduler.  All of the changes that we're making are designed to be backwards compatible for users, but still in the last release we ran into two issues.  One of these we caught before release (thanks to @sofroniewn / Napari folks) and one we found afterwards (thanks to @bnaul).  

These were both rapidly fixed, but highlight that we're likely to cause some downstream pain during this process, despite our best efforts.  There are several more PRs waiting to be merged here, each of which might cause similar amounts of churn.

We spoke about this briefly in the maintenance meeting today and considered two options:

1.  Pausing on releases for a few weeks while we settle HLG things
2.  Continuing HLG work into a separate development branch and merging it in afterwards

Folks decided to go for option 1, which means that we're planning to release the fix for the str_graph issue (thanks @mabsbk), let that settle for a day, and then not release again for 2-3 weeks.  I'm looking through the dask/distributed issue tracker to make sure that there isn't anything critical while I think @jsignell  is doing the same for dask/dask.

This might also be a good time to make the switch to Calver (cc @jcrist )

**Comment by jsignell** [comment]
I don't think there is anything major on dask/dask. If someone had time to poke at things, these seem close:
 - https://github.com/dask/dask/pull/6706 - conversation is ongoing
 - https://github.com/dask/dask/issues/6520 - conversation is stalled
 - https://github.com/dask/dask/pull/6680 - tests aren't passing.

**Comment by jrbourbeau** [comment]
Thanks for looking through open PRs @jsignell @mrocklin! Based on the number of 👍 it looks like there's agreement on releasing today. I'll start pushing out a Dask and Distributed release (`2.30.0`) in ~30 minutes

**Comment by jakirkham** [comment]
Sorry to bring this up now, but just now ran into a test failure on `distributed` `master`. Am writing up a bug report and will link here in a second.

**Comment by jakirkham** [comment]
Ok we think this was just bugs in the tests themselves. So shouldn't present an issue. Sorry for the noise 😞

**Comment by jrbourbeau** [comment]
Closing as 2.30.0 is out on PyPI, conda-forge, and Docker Hub. Thanks All!

**Comment by jakirkham** [comment]
Thanks James! 😄
